<?php

/**
 *
 * Somewhere to put snippets of test php code
 * cart
 *
 */
 
/**
 * Implements hook_commerce_cart_product_remove().
 * Check if we're removing a registration line item and delete the corresponding
 * registration so the user can sign up again without any errors.
 * @param  object $order     Commerce Order entity this item is attached to
 * @param  object $product   Commerce Product entity (REGISTRATION if reg item)
 * @param  int    $quantity  In the case of registration, number of tickets
 * @param  object $line_item Commerce Line Item entity (type = 'registration')
 * @return                   (none)
 */
function get_race_date {
    $race_date = getdate(strtotime("first Saturday of December")); 
    /**
     * Example content of $race_date:
     * 
     * print_r($race_date);
     * Array                                                                                                                                                                                    
     *(                                                                                                                                                                                        
     *    [seconds] => 0                                                                                                                                                                       
     *    [minutes] => 0                                                                                                                                                                       
     *    [hours] => 0                                                                                                                                                                         
     *    [mday] => 2                                                                                                                                                                          
     *    [wday] => 6                                                                                                                                                                          
     *    [mon] => 12                                                                                                                                                                          
     *    [year] => 2017                                                                                                                                                                       
     *    [yday] => 335                                                                                                                                                                        
     *    [weekday] => Saturday                                                                                                                                                                
     *    [month] => December                                                                                                                                                                  
     *    [0] => 1512172800                                                                                                                                                                    
     *)                                                                                                                                                                                        
     */
    $race_year = $race_date['year']; // This is numeric
}
/*
 * Code to put in a PHP filter of Drupal7 view
 * This will filter out data that's not for current year
 */
function filter_old_registrations {
    $race_date = getdate(strtotime("first Saturday of December"));
    $race_year = $race_date['year'];
    $reg_year = getdate($row->created)['year'];
    if ($reg_year < $race_year ) {
        return TRUE; // Rows where this returns true are not displayed
    }
    else {
        return FALSE;
    }
}
