$view = new view();
$view->name = 'event_entries_export';
$view->description = 'Entries Data Exports';
$view->tag = 'norwegian.blue, event entry';
$view->base_table = 'registration';
$view->human_name = 'Event Entries Export';
$view->core = 7;
$view->api_version = '3.0';
$view->disabled = FALSE; /* Edit this to true to make a default view disabled initially */

/* Display: Master */
$handler = $view->new_display('default', 'Master', 'default');
$handler->display->display_options['title'] = 'Manage Registrations';
$handler->display->display_options['css_class'] = 'manage-entries-wrapper';
$handler->display->display_options['use_more_always'] = FALSE;
$handler->display->display_options['access']['type'] = 'role';
$handler->display->display_options['access']['role'] = array(
  3 => '3',
  6 => '6',
);
$handler->display->display_options['cache']['type'] = 'none';
$handler->display->display_options['query']['type'] = 'views_query';
$handler->display->display_options['query']['options']['distinct'] = TRUE;
$handler->display->display_options['query']['options']['pure_distinct'] = TRUE;
$handler->display->display_options['exposed_form']['type'] = 'basic';
$handler->display->display_options['exposed_form']['options']['autosubmit_hide'] = FALSE;
$handler->display->display_options['pager']['type'] = 'full';
$handler->display->display_options['pager']['options']['items_per_page'] = '100';
$handler->display->display_options['pager']['options']['offset'] = '0';
$handler->display->display_options['pager']['options']['id'] = '0';
$handler->display->display_options['pager']['options']['quantity'] = '9';
$handler->display->display_options['style_plugin'] = 'table';
$handler->display->display_options['style_options']['columns'] = array(
  'title' => 'title',
  'registration_id' => 'registration_id',
  'field_first_name' => 'field_first_name',
  'field_family_name' => 'field_family_name',
  'mail' => 'mail',
  'field_gender' => 'field_gender',
  'field_date_of_birth' => 'field_date_of_birth',
  'field_age_on_race_day' => 'field_age_on_race_day',
  'type' => 'type',
  'rendered_entity' => 'rendered_entity',
  'field_ultra_experience' => 'field_ultra_experience',
  'rendered_entity_1' => 'rendered_entity_1',
  'state_edit' => 'state_edit',
  'user_uid' => 'user_uid',
);
$handler->display->display_options['style_options']['default'] = 'title';
$handler->display->display_options['style_options']['info'] = array(
  'title' => array(
    'sortable' => 1,
    'default_sort_order' => 'asc',
    'align' => '',
    'separator' => '',
    'empty_column' => 0,
  ),
  'registration_id' => array(
    'sortable' => 1,
    'default_sort_order' => 'asc',
    'align' => '',
    'separator' => '',
    'empty_column' => 0,
  ),
  'field_first_name' => array(
    'sortable' => 1,
    'default_sort_order' => 'asc',
    'align' => '',
    'separator' => '',
    'empty_column' => 0,
  ),
  'field_family_name' => array(
    'sortable' => 1,
    'default_sort_order' => 'asc',
    'align' => '',
    'separator' => '',
    'empty_column' => 0,
  ),
  'mail' => array(
    'sortable' => 1,
    'default_sort_order' => 'asc',
    'align' => '',
    'separator' => '',
    'empty_column' => 0,
  ),
  'field_gender' => array(
    'sortable' => 1,
    'default_sort_order' => 'asc',
    'align' => '',
    'separator' => '',
    'empty_column' => 0,
  ),
  'field_date_of_birth' => array(
    'sortable' => 1,
    'default_sort_order' => 'asc',
    'align' => '',
    'separator' => '',
    'empty_column' => 0,
  ),
  'field_age_on_race_day' => array(
    'sortable' => 1,
    'default_sort_order' => 'asc',
    'align' => '',
    'separator' => '',
    'empty_column' => 0,
  ),
  'type' => array(
    'sortable' => 1,
    'default_sort_order' => 'asc',
    'align' => '',
    'separator' => '',
    'empty_column' => 0,
  ),
  'rendered_entity' => array(
    'align' => '',
    'separator' => '',
    'empty_column' => 0,
  ),
  'field_ultra_experience' => array(
    'sortable' => 1,
    'default_sort_order' => 'asc',
    'align' => '',
    'separator' => '',
    'empty_column' => 0,
  ),
  'rendered_entity_1' => array(
    'align' => '',
    'separator' => '',
    'empty_column' => 0,
  ),
  'state_edit' => array(
    'align' => '',
    'separator' => '',
    'empty_column' => 0,
  ),
  'user_uid' => array(
    'sortable' => 1,
    'default_sort_order' => 'asc',
    'align' => '',
    'separator' => '',
    'empty_column' => 0,
  ),
);
$handler->display->display_options['style_options']['sticky'] = TRUE;
$handler->display->display_options['style_options']['empty_table'] = TRUE;
/* Header: Global: View area */
$handler->display->display_options['header']['view']['id'] = 'view';
$handler->display->display_options['header']['view']['table'] = 'views';
$handler->display->display_options['header']['view']['field'] = 'view';
$handler->display->display_options['header']['view']['label'] = 'Display Paces Taken';
$handler->display->display_options['header']['view']['view_to_insert'] = 'event_entry_places_taken_summary:default';
/* Header: Global: Text area */
$handler->display->display_options['header']['area']['id'] = 'area';
$handler->display->display_options['header']['area']['table'] = 'views';
$handler->display->display_options['header']['area']['field'] = 'area';
$handler->display->display_options['header']['area']['label'] = 'Filter info';
$handler->display->display_options['header']['area']['content'] = 'Apply filters to alter the type of result.
eg. Selecting keplerreg in the Event filter will only show KeplerChallenge registrations.
      or if you wanted to find all Charity runners, click  Charity under "Runner Type"
If you want to select more than one option in one filter use the Ctrl key (or Cmd on Mac)';
$handler->display->display_options['header']['area']['format'] = 'full_html';
/* Relationship: Registration: User */
$handler->display->display_options['relationships']['user_uid']['id'] = 'user_uid';
$handler->display->display_options['relationships']['user_uid']['table'] = 'registration';
$handler->display->display_options['relationships']['user_uid']['field'] = 'user_uid';
/* Relationship: User: Profile */
$handler->display->display_options['relationships']['profile']['id'] = 'profile';
$handler->display->display_options['relationships']['profile']['table'] = 'users';
$handler->display->display_options['relationships']['profile']['field'] = 'profile';
$handler->display->display_options['relationships']['profile']['relationship'] = 'user_uid';
$handler->display->display_options['relationships']['profile']['bundle_types'] = array(
  'main' => 'main',
);
/* Relationship: Registration: Registration to Node */
$handler->display->display_options['relationships']['registration_related_node']['id'] = 'registration_related_node';
$handler->display->display_options['relationships']['registration_related_node']['table'] = 'registration';
$handler->display->display_options['relationships']['registration_related_node']['field'] = 'registration_related_node';
/* Field: Content: Title */
$handler->display->display_options['fields']['title']['id'] = 'title';
$handler->display->display_options['fields']['title']['table'] = 'node';
$handler->display->display_options['fields']['title']['field'] = 'title';
$handler->display->display_options['fields']['title']['relationship'] = 'registration_related_node';
$handler->display->display_options['fields']['title']['label'] = 'Event';
$handler->display->display_options['fields']['title']['link_to_node'] = FALSE;
/* Field: Registration: Registration ID */
$handler->display->display_options['fields']['registration_id']['id'] = 'registration_id';
$handler->display->display_options['fields']['registration_id']['table'] = 'registration';
$handler->display->display_options['fields']['registration_id']['field'] = 'registration_id';
/* Field: User: E-mail */
$handler->display->display_options['fields']['mail']['id'] = 'mail';
$handler->display->display_options['fields']['mail']['table'] = 'users';
$handler->display->display_options['fields']['mail']['field'] = 'mail';
$handler->display->display_options['fields']['mail']['relationship'] = 'user_uid';
/* Field: Registration: Registration type */
$handler->display->display_options['fields']['type']['id'] = 'type';
$handler->display->display_options['fields']['type']['table'] = 'registration';
$handler->display->display_options['fields']['type']['field'] = 'type';
/* Field: Registration: Rendered Registration */
$handler->display->display_options['fields']['rendered_entity']['id'] = 'rendered_entity';
$handler->display->display_options['fields']['rendered_entity']['table'] = 'views_entity_registration';
$handler->display->display_options['fields']['rendered_entity']['field'] = 'rendered_entity';
$handler->display->display_options['fields']['rendered_entity']['link_to_entity'] = 1;
$handler->display->display_options['fields']['rendered_entity']['view_mode'] = 'full';
$handler->display->display_options['fields']['rendered_entity']['bypass_access'] = 0;
/* Field: Registration: State form field */
$handler->display->display_options['fields']['state_edit']['id'] = 'state_edit';
$handler->display->display_options['fields']['state_edit']['table'] = 'registration';
$handler->display->display_options['fields']['state_edit']['field'] = 'state_edit';
/* Field: Registration: User */
$handler->display->display_options['fields']['user_uid']['id'] = 'user_uid';
$handler->display->display_options['fields']['user_uid']['table'] = 'registration';
$handler->display->display_options['fields']['user_uid']['field'] = 'user_uid';
/* Field: Profile: URL */
$handler->display->display_options['fields']['url']['id'] = 'url';
$handler->display->display_options['fields']['url']['table'] = 'views_entity_profile2';
$handler->display->display_options['fields']['url']['field'] = 'url';
/* Field: Profile: Name &amp; Address - Country */
$handler->display->display_options['fields']['field_name_address_country']['id'] = 'field_name_address_country';
$handler->display->display_options['fields']['field_name_address_country']['table'] = 'field_data_field_name_address';
$handler->display->display_options['fields']['field_name_address_country']['field'] = 'field_name_address_country';
$handler->display->display_options['fields']['field_name_address_country']['relationship'] = 'profile';
/* Field: Profile: Name &amp; Address - First name */
$handler->display->display_options['fields']['field_name_address_first_name']['id'] = 'field_name_address_first_name';
$handler->display->display_options['fields']['field_name_address_first_name']['table'] = 'field_data_field_name_address';
$handler->display->display_options['fields']['field_name_address_first_name']['field'] = 'field_name_address_first_name';
$handler->display->display_options['fields']['field_name_address_first_name']['relationship'] = 'profile';
$handler->display->display_options['fields']['field_name_address_first_name']['label'] = 'First name';
/* Field: Profile: Name &amp; Address - Last name */
$handler->display->display_options['fields']['field_name_address_last_name']['id'] = 'field_name_address_last_name';
$handler->display->display_options['fields']['field_name_address_last_name']['table'] = 'field_data_field_name_address';
$handler->display->display_options['fields']['field_name_address_last_name']['field'] = 'field_name_address_last_name';
$handler->display->display_options['fields']['field_name_address_last_name']['relationship'] = 'profile';
$handler->display->display_options['fields']['field_name_address_last_name']['label'] = 'Last name';
/* Contextual filter: Content: Title */
$handler->display->display_options['arguments']['title']['id'] = 'title';
$handler->display->display_options['arguments']['title']['table'] = 'node';
$handler->display->display_options['arguments']['title']['field'] = 'title';
$handler->display->display_options['arguments']['title']['relationship'] = 'registration_related_node';
$handler->display->display_options['arguments']['title']['default_argument_type'] = 'fixed';
$handler->display->display_options['arguments']['title']['summary']['number_of_records'] = '0';
$handler->display->display_options['arguments']['title']['summary']['format'] = 'default_summary';
$handler->display->display_options['arguments']['title']['summary_options']['items_per_page'] = '25';
$handler->display->display_options['arguments']['title']['limit'] = '0';
/* Filter criterion: CurrentYear */
$handler->display->display_options['filters']['php']['id'] = 'php';
$handler->display->display_options['filters']['php']['table'] = 'views';
$handler->display->display_options['filters']['php']['field'] = 'php';
$handler->display->display_options['filters']['php']['ui_name'] = 'CurrentYear';
$handler->display->display_options['filters']['php']['use_php_setup'] = 0;
$handler->display->display_options['filters']['php']['php_filter'] = '    $race_date = getdate(strtotime("first Saturday of December"));
    $race_year = $race_date[\'year\'];
    $reg_year = getdate($row->created)[\'year\'];
    if ($reg_year < $race_year ) {
        return TRUE; // Rows where this returns true are not displayed
    }
    else {
        return FALSE;
    }';

/* Display: Export Missing Profiles */
$handler = $view->new_display('views_data_export', 'Export Missing Profiles', 'views_data_export_1');
$handler->display->display_options['enabled'] = FALSE;
$handler->display->display_options['pager']['type'] = 'some';
$handler->display->display_options['style_plugin'] = 'views_data_export_csv';
$handler->display->display_options['defaults']['fields'] = FALSE;
/* Field: Content: Title */
$handler->display->display_options['fields']['title']['id'] = 'title';
$handler->display->display_options['fields']['title']['table'] = 'node';
$handler->display->display_options['fields']['title']['field'] = 'title';
$handler->display->display_options['fields']['title']['relationship'] = 'registration_related_node';
$handler->display->display_options['fields']['title']['label'] = 'Event';
$handler->display->display_options['fields']['title']['exclude'] = TRUE;
$handler->display->display_options['fields']['title']['link_to_node'] = FALSE;
/* Field: Registration: Registration ID */
$handler->display->display_options['fields']['registration_id']['id'] = 'registration_id';
$handler->display->display_options['fields']['registration_id']['table'] = 'registration';
$handler->display->display_options['fields']['registration_id']['field'] = 'registration_id';
$handler->display->display_options['fields']['registration_id']['label'] = 'Reg ID';
/* Field: User: Name */
$handler->display->display_options['fields']['name']['id'] = 'name';
$handler->display->display_options['fields']['name']['table'] = 'users';
$handler->display->display_options['fields']['name']['field'] = 'name';
$handler->display->display_options['fields']['name']['relationship'] = 'user_uid';
/* Field: User: E-mail */
$handler->display->display_options['fields']['mail']['id'] = 'mail';
$handler->display->display_options['fields']['mail']['table'] = 'users';
$handler->display->display_options['fields']['mail']['field'] = 'mail';
$handler->display->display_options['fields']['mail']['relationship'] = 'user_uid';
/* Field: Registration: Registration type */
$handler->display->display_options['fields']['type']['id'] = 'type';
$handler->display->display_options['fields']['type']['table'] = 'registration';
$handler->display->display_options['fields']['type']['field'] = 'type';
$handler->display->display_options['fields']['type']['label'] = 'Event';
/* Field: Registration: Rendered Registration */
$handler->display->display_options['fields']['rendered_entity']['id'] = 'rendered_entity';
$handler->display->display_options['fields']['rendered_entity']['table'] = 'views_entity_registration';
$handler->display->display_options['fields']['rendered_entity']['field'] = 'rendered_entity';
$handler->display->display_options['fields']['rendered_entity']['exclude'] = TRUE;
$handler->display->display_options['fields']['rendered_entity']['link_to_entity'] = 1;
$handler->display->display_options['fields']['rendered_entity']['view_mode'] = 'full';
$handler->display->display_options['fields']['rendered_entity']['bypass_access'] = 0;
/* Field: Registration: User */
$handler->display->display_options['fields']['user_uid']['id'] = 'user_uid';
$handler->display->display_options['fields']['user_uid']['table'] = 'registration';
$handler->display->display_options['fields']['user_uid']['field'] = 'user_uid';
$handler->display->display_options['fields']['user_uid']['exclude'] = TRUE;
/* Field: Profile: URL */
$handler->display->display_options['fields']['url']['id'] = 'url';
$handler->display->display_options['fields']['url']['table'] = 'views_entity_profile2';
$handler->display->display_options['fields']['url']['field'] = 'url';
$handler->display->display_options['fields']['url']['relationship'] = 'profile';
$handler->display->display_options['fields']['url']['exclude'] = TRUE;
$handler->display->display_options['fields']['url']['link_to_entity'] = 0;
/* Field: Profile: Name &amp; Address - Country */
$handler->display->display_options['fields']['field_name_address_country']['id'] = 'field_name_address_country';
$handler->display->display_options['fields']['field_name_address_country']['table'] = 'field_data_field_name_address';
$handler->display->display_options['fields']['field_name_address_country']['field'] = 'field_name_address_country';
$handler->display->display_options['fields']['field_name_address_country']['relationship'] = 'profile';
$handler->display->display_options['fields']['field_name_address_country']['exclude'] = TRUE;
$handler->display->display_options['fields']['field_name_address_country']['display_name'] = 1;
/* Field: Profile: Name &amp; Address - First name */
$handler->display->display_options['fields']['field_name_address_first_name']['id'] = 'field_name_address_first_name';
$handler->display->display_options['fields']['field_name_address_first_name']['table'] = 'field_data_field_name_address';
$handler->display->display_options['fields']['field_name_address_first_name']['field'] = 'field_name_address_first_name';
$handler->display->display_options['fields']['field_name_address_first_name']['relationship'] = 'profile';
$handler->display->display_options['fields']['field_name_address_first_name']['label'] = 'First name';
$handler->display->display_options['fields']['field_name_address_first_name']['exclude'] = TRUE;
/* Field: Profile: Name &amp; Address - Last name */
$handler->display->display_options['fields']['field_name_address_last_name']['id'] = 'field_name_address_last_name';
$handler->display->display_options['fields']['field_name_address_last_name']['table'] = 'field_data_field_name_address';
$handler->display->display_options['fields']['field_name_address_last_name']['field'] = 'field_name_address_last_name';
$handler->display->display_options['fields']['field_name_address_last_name']['relationship'] = 'profile';
$handler->display->display_options['fields']['field_name_address_last_name']['label'] = 'Last name';
$handler->display->display_options['fields']['field_name_address_last_name']['exclude'] = TRUE;
/* Field: Registration: State entity */
$handler->display->display_options['fields']['state']['id'] = 'state';
$handler->display->display_options['fields']['state']['table'] = 'registration';
$handler->display->display_options['fields']['state']['field'] = 'state';
$handler->display->display_options['fields']['state']['label'] = 'Status';
$handler->display->display_options['defaults']['filter_groups'] = FALSE;
$handler->display->display_options['defaults']['filters'] = FALSE;
/* Filter criterion: Profile: Name &amp; Address - Last name */
$handler->display->display_options['filters']['field_name_address_last_name']['id'] = 'field_name_address_last_name';
$handler->display->display_options['filters']['field_name_address_last_name']['table'] = 'field_data_field_name_address';
$handler->display->display_options['filters']['field_name_address_last_name']['field'] = 'field_name_address_last_name';
$handler->display->display_options['filters']['field_name_address_last_name']['relationship'] = 'profile';
$handler->display->display_options['filters']['field_name_address_last_name']['operator'] = 'empty';
$handler->display->display_options['path'] = 'admin/data_export/missing_profiles.csv';

/* Display: Kepler Waitlist Export */
$handler = $view->new_display('views_data_export', 'Kepler Waitlist Export', 'views_data_export_2');
$handler->display->display_options['enabled'] = FALSE;
$handler->display->display_options['pager']['type'] = 'none';
$handler->display->display_options['pager']['options']['offset'] = '0';
$handler->display->display_options['style_plugin'] = 'views_data_export_csv';
$handler->display->display_options['defaults']['fields'] = FALSE;
/* Field: Global: View result counter */
$handler->display->display_options['fields']['counter']['id'] = 'counter';
$handler->display->display_options['fields']['counter']['table'] = 'views';
$handler->display->display_options['fields']['counter']['field'] = 'counter';
$handler->display->display_options['fields']['counter']['label'] = 'Counter';
$handler->display->display_options['fields']['counter']['counter_start'] = '1';
$handler->display->display_options['fields']['counter']['reverse'] = 0;
/* Field: Registration: Registration ID */
$handler->display->display_options['fields']['registration_id']['id'] = 'registration_id';
$handler->display->display_options['fields']['registration_id']['table'] = 'registration';
$handler->display->display_options['fields']['registration_id']['field'] = 'registration_id';
$handler->display->display_options['fields']['registration_id']['separator'] = '';
/* Field: Registration: User */
$handler->display->display_options['fields']['user_uid']['id'] = 'user_uid';
$handler->display->display_options['fields']['user_uid']['table'] = 'registration';
$handler->display->display_options['fields']['user_uid']['field'] = 'user_uid';
$handler->display->display_options['fields']['user_uid']['separator'] = '';
/* Field: Profile: Name &amp; Address - First name */
$handler->display->display_options['fields']['field_name_address_first_name']['id'] = 'field_name_address_first_name';
$handler->display->display_options['fields']['field_name_address_first_name']['table'] = 'field_data_field_name_address';
$handler->display->display_options['fields']['field_name_address_first_name']['field'] = 'field_name_address_first_name';
$handler->display->display_options['fields']['field_name_address_first_name']['relationship'] = 'profile';
$handler->display->display_options['fields']['field_name_address_first_name']['label'] = 'First name';
/* Field: Profile: Name &amp; Address - Last name */
$handler->display->display_options['fields']['field_name_address_last_name']['id'] = 'field_name_address_last_name';
$handler->display->display_options['fields']['field_name_address_last_name']['table'] = 'field_data_field_name_address';
$handler->display->display_options['fields']['field_name_address_last_name']['field'] = 'field_name_address_last_name';
$handler->display->display_options['fields']['field_name_address_last_name']['relationship'] = 'profile';
$handler->display->display_options['fields']['field_name_address_last_name']['label'] = 'Last name';
/* Field: Profile: Name &amp; Address - Locality (i.e. City) */
$handler->display->display_options['fields']['field_name_address_locality']['id'] = 'field_name_address_locality';
$handler->display->display_options['fields']['field_name_address_locality']['table'] = 'field_data_field_name_address';
$handler->display->display_options['fields']['field_name_address_locality']['field'] = 'field_name_address_locality';
$handler->display->display_options['fields']['field_name_address_locality']['relationship'] = 'profile';
$handler->display->display_options['fields']['field_name_address_locality']['label'] = 'City';
/* Field: Profile: Name &amp; Address - Country */
$handler->display->display_options['fields']['field_name_address_country']['id'] = 'field_name_address_country';
$handler->display->display_options['fields']['field_name_address_country']['table'] = 'field_data_field_name_address';
$handler->display->display_options['fields']['field_name_address_country']['field'] = 'field_name_address_country';
$handler->display->display_options['fields']['field_name_address_country']['relationship'] = 'profile';
/* Field: User: E-mail */
$handler->display->display_options['fields']['mail']['id'] = 'mail';
$handler->display->display_options['fields']['mail']['table'] = 'users';
$handler->display->display_options['fields']['mail']['field'] = 'mail';
$handler->display->display_options['fields']['mail']['relationship'] = 'user_uid';
/* Field: Registration: Runner Type */
$handler->display->display_options['fields']['field_runner_type']['id'] = 'field_runner_type';
$handler->display->display_options['fields']['field_runner_type']['table'] = 'field_data_field_runner_type';
$handler->display->display_options['fields']['field_runner_type']['field'] = 'field_runner_type';
/* Field: Registration: Registration type */
$handler->display->display_options['fields']['type']['id'] = 'type';
$handler->display->display_options['fields']['type']['table'] = 'registration';
$handler->display->display_options['fields']['type']['field'] = 'type';
/* Field: Registration: Rendered Registration */
$handler->display->display_options['fields']['rendered_entity']['id'] = 'rendered_entity';
$handler->display->display_options['fields']['rendered_entity']['table'] = 'views_entity_registration';
$handler->display->display_options['fields']['rendered_entity']['field'] = 'rendered_entity';
$handler->display->display_options['fields']['rendered_entity']['exclude'] = TRUE;
$handler->display->display_options['fields']['rendered_entity']['link_to_entity'] = 1;
$handler->display->display_options['fields']['rendered_entity']['view_mode'] = 'full';
$handler->display->display_options['fields']['rendered_entity']['bypass_access'] = 0;
/* Field: Profile: Gender */
$handler->display->display_options['fields']['field_gender']['id'] = 'field_gender';
$handler->display->display_options['fields']['field_gender']['table'] = 'field_data_field_gender';
$handler->display->display_options['fields']['field_gender']['field'] = 'field_gender';
$handler->display->display_options['fields']['field_gender']['relationship'] = 'profile';
/* Field: Registration: Est. Time this year */
$handler->display->display_options['fields']['field_est_time_this_year']['id'] = 'field_est_time_this_year';
$handler->display->display_options['fields']['field_est_time_this_year']['table'] = 'field_data_field_est_time_this_year';
$handler->display->display_options['fields']['field_est_time_this_year']['field'] = 'field_est_time_this_year';
$handler->display->display_options['fields']['field_est_time_this_year']['settings'] = array(
  'format_type' => 'timeonly',
  'fromto' => 'both',
  'multiple_number' => '',
  'multiple_from' => '',
  'multiple_to' => '',
  'show_remaining_days' => 0,
);
/* Field: Registration: Previous best result */
$handler->display->display_options['fields']['field_previous_best_time']['id'] = 'field_previous_best_time';
$handler->display->display_options['fields']['field_previous_best_time']['table'] = 'field_data_field_previous_best_time';
$handler->display->display_options['fields']['field_previous_best_time']['field'] = 'field_previous_best_time';
$handler->display->display_options['fields']['field_previous_best_time']['settings'] = array(
  'format_type' => 'timeonly',
  'fromto' => 'both',
  'multiple_number' => '',
  'multiple_from' => '',
  'multiple_to' => '',
  'show_remaining_days' => 0,
);
/* Field: Registration: No of Prev events */
$handler->display->display_options['fields']['field_no_of_prev_events']['id'] = 'field_no_of_prev_events';
$handler->display->display_options['fields']['field_no_of_prev_events']['table'] = 'field_data_field_no_of_prev_events';
$handler->display->display_options['fields']['field_no_of_prev_events']['field'] = 'field_no_of_prev_events';
/* Field: Registration: Medal Year */
$handler->display->display_options['fields']['field_medal_year']['id'] = 'field_medal_year';
$handler->display->display_options['fields']['field_medal_year']['table'] = 'field_data_field_medal_year';
$handler->display->display_options['fields']['field_medal_year']['field'] = 'field_medal_year';
/* Field: Registration: Notes */
$handler->display->display_options['fields']['field_notes']['id'] = 'field_notes';
$handler->display->display_options['fields']['field_notes']['table'] = 'field_data_field_notes';
$handler->display->display_options['fields']['field_notes']['field'] = 'field_notes';
/* Field: Registration: Tags */
$handler->display->display_options['fields']['field_tags']['id'] = 'field_tags';
$handler->display->display_options['fields']['field_tags']['table'] = 'field_data_field_tags';
$handler->display->display_options['fields']['field_tags']['field'] = 'field_tags';
$handler->display->display_options['fields']['field_tags']['type'] = 'taxonomy_term_reference_plain';
$handler->display->display_options['fields']['field_tags']['delta_offset'] = '0';
/* Field: Profile: Running profile */
$handler->display->display_options['fields']['field_running_profile']['id'] = 'field_running_profile';
$handler->display->display_options['fields']['field_running_profile']['table'] = 'field_data_field_running_profile';
$handler->display->display_options['fields']['field_running_profile']['field'] = 'field_running_profile';
$handler->display->display_options['fields']['field_running_profile']['relationship'] = 'profile';
/* Field: Profile: Commentary */
$handler->display->display_options['fields']['field_commentary']['id'] = 'field_commentary';
$handler->display->display_options['fields']['field_commentary']['table'] = 'field_data_field_commentary';
$handler->display->display_options['fields']['field_commentary']['field'] = 'field_commentary';
$handler->display->display_options['fields']['field_commentary']['relationship'] = 'profile';
/* Field: Registration: Date updated */
$handler->display->display_options['fields']['updated']['id'] = 'updated';
$handler->display->display_options['fields']['updated']['table'] = 'registration';
$handler->display->display_options['fields']['updated']['field'] = 'updated';
$handler->display->display_options['fields']['updated']['date_format'] = 'short';
$handler->display->display_options['fields']['updated']['second_date_format'] = 'long';
$handler->display->display_options['defaults']['filter_groups'] = FALSE;
$handler->display->display_options['defaults']['filters'] = FALSE;
/* Filter criterion: Registration: State entity */
$handler->display->display_options['filters']['state']['id'] = 'state';
$handler->display->display_options['filters']['state']['table'] = 'registration';
$handler->display->display_options['filters']['state']['field'] = 'state';
$handler->display->display_options['filters']['state']['value'] = array(
  'waitlist' => 'waitlist',
);
/* Filter criterion: Registration: Registration type */
$handler->display->display_options['filters']['type']['id'] = 'type';
$handler->display->display_options['filters']['type']['table'] = 'registration';
$handler->display->display_options['filters']['type']['field'] = 'type';
$handler->display->display_options['filters']['type']['value'] = array(
  'keplerreg' => 'keplerreg',
);
$handler->display->display_options['path'] = 'admin/data_export/kepler_waitlist.csv';

/* Display: Grunt Waitlist Export */
$handler = $view->new_display('views_data_export', 'Grunt Waitlist Export', 'views_data_export_3');
$handler->display->display_options['enabled'] = FALSE;
$handler->display->display_options['pager']['type'] = 'none';
$handler->display->display_options['pager']['options']['offset'] = '0';
$handler->display->display_options['style_plugin'] = 'views_data_export_csv';
$handler->display->display_options['defaults']['fields'] = FALSE;
/* Field: Global: View result counter */
$handler->display->display_options['fields']['counter']['id'] = 'counter';
$handler->display->display_options['fields']['counter']['table'] = 'views';
$handler->display->display_options['fields']['counter']['field'] = 'counter';
$handler->display->display_options['fields']['counter']['label'] = 'Counter';
$handler->display->display_options['fields']['counter']['counter_start'] = '1';
$handler->display->display_options['fields']['counter']['reverse'] = 0;
/* Field: Registration: Registration ID */
$handler->display->display_options['fields']['registration_id']['id'] = 'registration_id';
$handler->display->display_options['fields']['registration_id']['table'] = 'registration';
$handler->display->display_options['fields']['registration_id']['field'] = 'registration_id';
$handler->display->display_options['fields']['registration_id']['separator'] = '';
/* Field: Registration: User */
$handler->display->display_options['fields']['user_uid']['id'] = 'user_uid';
$handler->display->display_options['fields']['user_uid']['table'] = 'registration';
$handler->display->display_options['fields']['user_uid']['field'] = 'user_uid';
$handler->display->display_options['fields']['user_uid']['separator'] = '';
/* Field: Profile: Name &amp; Address - First name */
$handler->display->display_options['fields']['field_name_address_first_name']['id'] = 'field_name_address_first_name';
$handler->display->display_options['fields']['field_name_address_first_name']['table'] = 'field_data_field_name_address';
$handler->display->display_options['fields']['field_name_address_first_name']['field'] = 'field_name_address_first_name';
$handler->display->display_options['fields']['field_name_address_first_name']['relationship'] = 'profile';
$handler->display->display_options['fields']['field_name_address_first_name']['label'] = 'First name';
/* Field: Profile: Name &amp; Address - Last name */
$handler->display->display_options['fields']['field_name_address_last_name']['id'] = 'field_name_address_last_name';
$handler->display->display_options['fields']['field_name_address_last_name']['table'] = 'field_data_field_name_address';
$handler->display->display_options['fields']['field_name_address_last_name']['field'] = 'field_name_address_last_name';
$handler->display->display_options['fields']['field_name_address_last_name']['relationship'] = 'profile';
$handler->display->display_options['fields']['field_name_address_last_name']['label'] = 'Last name';
/* Field: Profile: Name &amp; Address - Locality (i.e. City) */
$handler->display->display_options['fields']['field_name_address_locality']['id'] = 'field_name_address_locality';
$handler->display->display_options['fields']['field_name_address_locality']['table'] = 'field_data_field_name_address';
$handler->display->display_options['fields']['field_name_address_locality']['field'] = 'field_name_address_locality';
$handler->display->display_options['fields']['field_name_address_locality']['relationship'] = 'profile';
$handler->display->display_options['fields']['field_name_address_locality']['label'] = 'City';
/* Field: Profile: Name &amp; Address - Country */
$handler->display->display_options['fields']['field_name_address_country']['id'] = 'field_name_address_country';
$handler->display->display_options['fields']['field_name_address_country']['table'] = 'field_data_field_name_address';
$handler->display->display_options['fields']['field_name_address_country']['field'] = 'field_name_address_country';
$handler->display->display_options['fields']['field_name_address_country']['relationship'] = 'profile';
/* Field: User: E-mail */
$handler->display->display_options['fields']['mail']['id'] = 'mail';
$handler->display->display_options['fields']['mail']['table'] = 'users';
$handler->display->display_options['fields']['mail']['field'] = 'mail';
$handler->display->display_options['fields']['mail']['relationship'] = 'user_uid';
/* Field: Registration: Runner Type */
$handler->display->display_options['fields']['field_runner_type']['id'] = 'field_runner_type';
$handler->display->display_options['fields']['field_runner_type']['table'] = 'field_data_field_runner_type';
$handler->display->display_options['fields']['field_runner_type']['field'] = 'field_runner_type';
/* Field: Registration: Registration type */
$handler->display->display_options['fields']['type']['id'] = 'type';
$handler->display->display_options['fields']['type']['table'] = 'registration';
$handler->display->display_options['fields']['type']['field'] = 'type';
/* Field: Registration: Rendered Registration */
$handler->display->display_options['fields']['rendered_entity']['id'] = 'rendered_entity';
$handler->display->display_options['fields']['rendered_entity']['table'] = 'views_entity_registration';
$handler->display->display_options['fields']['rendered_entity']['field'] = 'rendered_entity';
$handler->display->display_options['fields']['rendered_entity']['exclude'] = TRUE;
$handler->display->display_options['fields']['rendered_entity']['link_to_entity'] = 1;
$handler->display->display_options['fields']['rendered_entity']['view_mode'] = 'full';
$handler->display->display_options['fields']['rendered_entity']['bypass_access'] = 0;
/* Field: Profile: Gender */
$handler->display->display_options['fields']['field_gender']['id'] = 'field_gender';
$handler->display->display_options['fields']['field_gender']['table'] = 'field_data_field_gender';
$handler->display->display_options['fields']['field_gender']['field'] = 'field_gender';
$handler->display->display_options['fields']['field_gender']['relationship'] = 'profile';
/* Field: Registration: Est. Time this year */
$handler->display->display_options['fields']['field_est_time_this_year']['id'] = 'field_est_time_this_year';
$handler->display->display_options['fields']['field_est_time_this_year']['table'] = 'field_data_field_est_time_this_year';
$handler->display->display_options['fields']['field_est_time_this_year']['field'] = 'field_est_time_this_year';
$handler->display->display_options['fields']['field_est_time_this_year']['settings'] = array(
  'format_type' => 'timeonly',
  'fromto' => 'both',
  'multiple_number' => '',
  'multiple_from' => '',
  'multiple_to' => '',
  'show_remaining_days' => 0,
);
/* Field: Registration: Previous best result */
$handler->display->display_options['fields']['field_previous_best_time']['id'] = 'field_previous_best_time';
$handler->display->display_options['fields']['field_previous_best_time']['table'] = 'field_data_field_previous_best_time';
$handler->display->display_options['fields']['field_previous_best_time']['field'] = 'field_previous_best_time';
$handler->display->display_options['fields']['field_previous_best_time']['settings'] = array(
  'format_type' => 'timeonly',
  'fromto' => 'both',
  'multiple_number' => '',
  'multiple_from' => '',
  'multiple_to' => '',
  'show_remaining_days' => 0,
);
/* Field: Registration: No of Prev events */
$handler->display->display_options['fields']['field_no_of_prev_events']['id'] = 'field_no_of_prev_events';
$handler->display->display_options['fields']['field_no_of_prev_events']['table'] = 'field_data_field_no_of_prev_events';
$handler->display->display_options['fields']['field_no_of_prev_events']['field'] = 'field_no_of_prev_events';
/* Field: Registration: Medal Year */
$handler->display->display_options['fields']['field_medal_year']['id'] = 'field_medal_year';
$handler->display->display_options['fields']['field_medal_year']['table'] = 'field_data_field_medal_year';
$handler->display->display_options['fields']['field_medal_year']['field'] = 'field_medal_year';
/* Field: Registration: Notes */
$handler->display->display_options['fields']['field_notes']['id'] = 'field_notes';
$handler->display->display_options['fields']['field_notes']['table'] = 'field_data_field_notes';
$handler->display->display_options['fields']['field_notes']['field'] = 'field_notes';
/* Field: Registration: Tags */
$handler->display->display_options['fields']['field_tags']['id'] = 'field_tags';
$handler->display->display_options['fields']['field_tags']['table'] = 'field_data_field_tags';
$handler->display->display_options['fields']['field_tags']['field'] = 'field_tags';
$handler->display->display_options['fields']['field_tags']['type'] = 'taxonomy_term_reference_plain';
$handler->display->display_options['fields']['field_tags']['delta_offset'] = '0';
/* Field: Profile: Running profile */
$handler->display->display_options['fields']['field_running_profile']['id'] = 'field_running_profile';
$handler->display->display_options['fields']['field_running_profile']['table'] = 'field_data_field_running_profile';
$handler->display->display_options['fields']['field_running_profile']['field'] = 'field_running_profile';
$handler->display->display_options['fields']['field_running_profile']['relationship'] = 'profile';
/* Field: Profile: Commentary */
$handler->display->display_options['fields']['field_commentary']['id'] = 'field_commentary';
$handler->display->display_options['fields']['field_commentary']['table'] = 'field_data_field_commentary';
$handler->display->display_options['fields']['field_commentary']['field'] = 'field_commentary';
$handler->display->display_options['fields']['field_commentary']['relationship'] = 'profile';
/* Field: Registration: Date updated */
$handler->display->display_options['fields']['updated']['id'] = 'updated';
$handler->display->display_options['fields']['updated']['table'] = 'registration';
$handler->display->display_options['fields']['updated']['field'] = 'updated';
$handler->display->display_options['fields']['updated']['date_format'] = 'short';
$handler->display->display_options['fields']['updated']['second_date_format'] = 'long';
$handler->display->display_options['defaults']['filter_groups'] = FALSE;
$handler->display->display_options['defaults']['filters'] = FALSE;
/* Filter criterion: Registration: State entity */
$handler->display->display_options['filters']['state']['id'] = 'state';
$handler->display->display_options['filters']['state']['table'] = 'registration';
$handler->display->display_options['filters']['state']['field'] = 'state';
$handler->display->display_options['filters']['state']['value'] = array(
  'waitlist' => 'waitlist',
);
/* Filter criterion: Registration: Registration type */
$handler->display->display_options['filters']['type']['id'] = 'type';
$handler->display->display_options['filters']['type']['table'] = 'registration';
$handler->display->display_options['filters']['type']['field'] = 'type';
$handler->display->display_options['filters']['type']['value'] = array(
  'gruntreg' => 'gruntreg',
);
$handler->display->display_options['path'] = 'admin/data_export/grunt_waitlist.csv';

/* Display: Mailchimp Export */
$handler = $view->new_display('views_data_export', 'Mailchimp Export', 'views_data_export_4');
$handler->display->display_options['defaults']['title'] = FALSE;
$handler->display->display_options['title'] = 'Mailchimp Export';
$handler->display->display_options['enabled'] = FALSE;
$handler->display->display_options['display_description'] = 'Runner Export for Mailchimp';
$handler->display->display_options['pager']['type'] = 'none';
$handler->display->display_options['pager']['options']['offset'] = '0';
$handler->display->display_options['style_plugin'] = 'views_data_export_csv';
$handler->display->display_options['defaults']['fields'] = FALSE;
/* Field: Global: View result counter */
$handler->display->display_options['fields']['counter']['id'] = 'counter';
$handler->display->display_options['fields']['counter']['table'] = 'views';
$handler->display->display_options['fields']['counter']['field'] = 'counter';
$handler->display->display_options['fields']['counter']['label'] = 'Counter';
$handler->display->display_options['fields']['counter']['counter_start'] = '1';
$handler->display->display_options['fields']['counter']['reverse'] = 0;
/* Field: Registration: Registration ID */
$handler->display->display_options['fields']['registration_id']['id'] = 'registration_id';
$handler->display->display_options['fields']['registration_id']['table'] = 'registration';
$handler->display->display_options['fields']['registration_id']['field'] = 'registration_id';
$handler->display->display_options['fields']['registration_id']['exclude'] = TRUE;
$handler->display->display_options['fields']['registration_id']['separator'] = '';
/* Field: Registration: User */
$handler->display->display_options['fields']['user_uid']['id'] = 'user_uid';
$handler->display->display_options['fields']['user_uid']['table'] = 'registration';
$handler->display->display_options['fields']['user_uid']['field'] = 'user_uid';
$handler->display->display_options['fields']['user_uid']['separator'] = '';
/* Field: Profile: Name &amp; Address - First name */
$handler->display->display_options['fields']['field_name_address_first_name']['id'] = 'field_name_address_first_name';
$handler->display->display_options['fields']['field_name_address_first_name']['table'] = 'field_data_field_name_address';
$handler->display->display_options['fields']['field_name_address_first_name']['field'] = 'field_name_address_first_name';
$handler->display->display_options['fields']['field_name_address_first_name']['relationship'] = 'profile';
$handler->display->display_options['fields']['field_name_address_first_name']['label'] = 'First name';
/* Field: Profile: Name &amp; Address - Last name */
$handler->display->display_options['fields']['field_name_address_last_name']['id'] = 'field_name_address_last_name';
$handler->display->display_options['fields']['field_name_address_last_name']['table'] = 'field_data_field_name_address';
$handler->display->display_options['fields']['field_name_address_last_name']['field'] = 'field_name_address_last_name';
$handler->display->display_options['fields']['field_name_address_last_name']['relationship'] = 'profile';
$handler->display->display_options['fields']['field_name_address_last_name']['label'] = 'Last name';
/* Field: Profile: Name &amp; Address - Locality (i.e. City) */
$handler->display->display_options['fields']['field_name_address_locality']['id'] = 'field_name_address_locality';
$handler->display->display_options['fields']['field_name_address_locality']['table'] = 'field_data_field_name_address';
$handler->display->display_options['fields']['field_name_address_locality']['field'] = 'field_name_address_locality';
$handler->display->display_options['fields']['field_name_address_locality']['relationship'] = 'profile';
$handler->display->display_options['fields']['field_name_address_locality']['label'] = 'City';
/* Field: Profile: Name &amp; Address - Country */
$handler->display->display_options['fields']['field_name_address_country']['id'] = 'field_name_address_country';
$handler->display->display_options['fields']['field_name_address_country']['table'] = 'field_data_field_name_address';
$handler->display->display_options['fields']['field_name_address_country']['field'] = 'field_name_address_country';
$handler->display->display_options['fields']['field_name_address_country']['relationship'] = 'profile';
$handler->display->display_options['fields']['field_name_address_country']['label'] = 'Country';
$handler->display->display_options['fields']['field_name_address_country']['display_name'] = 1;
/* Field: User: E-mail */
$handler->display->display_options['fields']['mail']['id'] = 'mail';
$handler->display->display_options['fields']['mail']['table'] = 'users';
$handler->display->display_options['fields']['mail']['field'] = 'mail';
$handler->display->display_options['fields']['mail']['relationship'] = 'user_uid';
/* Field: Registration: State entity */
$handler->display->display_options['fields']['state']['id'] = 'state';
$handler->display->display_options['fields']['state']['table'] = 'registration';
$handler->display->display_options['fields']['state']['field'] = 'state';
$handler->display->display_options['fields']['state']['label'] = 'Status';
/* Field: Registration: Runner Type */
$handler->display->display_options['fields']['field_runner_type']['id'] = 'field_runner_type';
$handler->display->display_options['fields']['field_runner_type']['table'] = 'field_data_field_runner_type';
$handler->display->display_options['fields']['field_runner_type']['field'] = 'field_runner_type';
/* Field: Registration: Registration type */
$handler->display->display_options['fields']['type']['id'] = 'type';
$handler->display->display_options['fields']['type']['table'] = 'registration';
$handler->display->display_options['fields']['type']['field'] = 'type';
/* Field: Profile: Gender */
$handler->display->display_options['fields']['field_gender']['id'] = 'field_gender';
$handler->display->display_options['fields']['field_gender']['table'] = 'field_data_field_gender';
$handler->display->display_options['fields']['field_gender']['field'] = 'field_gender';
$handler->display->display_options['fields']['field_gender']['relationship'] = 'profile';
$handler->display->display_options['defaults']['arguments'] = FALSE;
/* Contextual filter: Content: Title */
$handler->display->display_options['arguments']['title']['id'] = 'title';
$handler->display->display_options['arguments']['title']['table'] = 'node';
$handler->display->display_options['arguments']['title']['field'] = 'title';
$handler->display->display_options['arguments']['title']['relationship'] = 'registration_related_node';
$handler->display->display_options['arguments']['title']['default_argument_type'] = 'fixed';
$handler->display->display_options['arguments']['title']['summary']['number_of_records'] = '0';
$handler->display->display_options['arguments']['title']['summary']['format'] = 'default_summary';
$handler->display->display_options['arguments']['title']['summary_options']['items_per_page'] = '25';
$handler->display->display_options['arguments']['title']['limit'] = '0';
/* Contextual filter: Registration: Event Date (field_year) */
$handler->display->display_options['arguments']['field_year_value']['id'] = 'field_year_value';
$handler->display->display_options['arguments']['field_year_value']['table'] = 'field_data_field_year';
$handler->display->display_options['arguments']['field_year_value']['field'] = 'field_year_value';
$handler->display->display_options['arguments']['field_year_value']['default_action'] = 'default';
$handler->display->display_options['arguments']['field_year_value']['default_argument_type'] = 'php';
$handler->display->display_options['arguments']['field_year_value']['default_argument_options']['code'] = 'echo date("Y"); ';
$handler->display->display_options['arguments']['field_year_value']['summary']['number_of_records'] = '0';
$handler->display->display_options['arguments']['field_year_value']['summary']['format'] = 'default_summary';
$handler->display->display_options['arguments']['field_year_value']['summary_options']['items_per_page'] = '25';
$handler->display->display_options['arguments']['field_year_value']['limit'] = '0';
$handler->display->display_options['defaults']['filter_groups'] = FALSE;
$handler->display->display_options['defaults']['filters'] = FALSE;
/* Filter criterion: Registration: State entity */
$handler->display->display_options['filters']['state']['id'] = 'state';
$handler->display->display_options['filters']['state']['table'] = 'registration';
$handler->display->display_options['filters']['state']['field'] = 'state';
$handler->display->display_options['filters']['state']['value'] = array(
  'waitlist' => 'waitlist',
  'invited' => 'invited',
  'complete' => 'complete',
  'paid' => 'paid',
  'canceled' => 'canceled',
);
$handler->display->display_options['path'] = 'admin/data_export/mailchimp.csv';
$handler->display->display_options['sitename_title'] = 0;

/* Display: Medalists Export */
$handler = $view->new_display('views_data_export', 'Medalists Export', 'views_data_export_5');
$handler->display->display_options['defaults']['title'] = FALSE;
$handler->display->display_options['title'] = 'Medalists Export';
$handler->display->display_options['enabled'] = FALSE;
$handler->display->display_options['display_description'] = 'Runner Export - medalists';
$handler->display->display_options['pager']['type'] = 'none';
$handler->display->display_options['pager']['options']['offset'] = '0';
$handler->display->display_options['style_plugin'] = 'views_data_export_csv';
$handler->display->display_options['defaults']['fields'] = FALSE;
/* Field: Global: View result counter */
$handler->display->display_options['fields']['counter']['id'] = 'counter';
$handler->display->display_options['fields']['counter']['table'] = 'views';
$handler->display->display_options['fields']['counter']['field'] = 'counter';
$handler->display->display_options['fields']['counter']['label'] = 'Counter';
$handler->display->display_options['fields']['counter']['counter_start'] = '1';
$handler->display->display_options['fields']['counter']['reverse'] = 0;
/* Field: Registration: Registration ID */
$handler->display->display_options['fields']['registration_id']['id'] = 'registration_id';
$handler->display->display_options['fields']['registration_id']['table'] = 'registration';
$handler->display->display_options['fields']['registration_id']['field'] = 'registration_id';
$handler->display->display_options['fields']['registration_id']['exclude'] = TRUE;
$handler->display->display_options['fields']['registration_id']['separator'] = '';
/* Field: Registration: User */
$handler->display->display_options['fields']['user_uid']['id'] = 'user_uid';
$handler->display->display_options['fields']['user_uid']['table'] = 'registration';
$handler->display->display_options['fields']['user_uid']['field'] = 'user_uid';
$handler->display->display_options['fields']['user_uid']['separator'] = '';
/* Field: Profile: Name &amp; Address - First name */
$handler->display->display_options['fields']['field_name_address_first_name']['id'] = 'field_name_address_first_name';
$handler->display->display_options['fields']['field_name_address_first_name']['table'] = 'field_data_field_name_address';
$handler->display->display_options['fields']['field_name_address_first_name']['field'] = 'field_name_address_first_name';
$handler->display->display_options['fields']['field_name_address_first_name']['relationship'] = 'profile';
$handler->display->display_options['fields']['field_name_address_first_name']['label'] = 'First name';
/* Field: Profile: Name &amp; Address - Last name */
$handler->display->display_options['fields']['field_name_address_last_name']['id'] = 'field_name_address_last_name';
$handler->display->display_options['fields']['field_name_address_last_name']['table'] = 'field_data_field_name_address';
$handler->display->display_options['fields']['field_name_address_last_name']['field'] = 'field_name_address_last_name';
$handler->display->display_options['fields']['field_name_address_last_name']['relationship'] = 'profile';
$handler->display->display_options['fields']['field_name_address_last_name']['label'] = 'Last name';
/* Field: Profile: Name &amp; Address - Locality (i.e. City) */
$handler->display->display_options['fields']['field_name_address_locality']['id'] = 'field_name_address_locality';
$handler->display->display_options['fields']['field_name_address_locality']['table'] = 'field_data_field_name_address';
$handler->display->display_options['fields']['field_name_address_locality']['field'] = 'field_name_address_locality';
$handler->display->display_options['fields']['field_name_address_locality']['relationship'] = 'profile';
$handler->display->display_options['fields']['field_name_address_locality']['label'] = 'City';
/* Field: Profile: Name &amp; Address - Country */
$handler->display->display_options['fields']['field_name_address_country']['id'] = 'field_name_address_country';
$handler->display->display_options['fields']['field_name_address_country']['table'] = 'field_data_field_name_address';
$handler->display->display_options['fields']['field_name_address_country']['field'] = 'field_name_address_country';
$handler->display->display_options['fields']['field_name_address_country']['relationship'] = 'profile';
$handler->display->display_options['fields']['field_name_address_country']['label'] = 'Country';
$handler->display->display_options['fields']['field_name_address_country']['display_name'] = 1;
/* Field: User: E-mail */
$handler->display->display_options['fields']['mail']['id'] = 'mail';
$handler->display->display_options['fields']['mail']['table'] = 'users';
$handler->display->display_options['fields']['mail']['field'] = 'mail';
$handler->display->display_options['fields']['mail']['relationship'] = 'user_uid';
/* Field: Registration: State entity */
$handler->display->display_options['fields']['state']['id'] = 'state';
$handler->display->display_options['fields']['state']['table'] = 'registration';
$handler->display->display_options['fields']['state']['field'] = 'state';
$handler->display->display_options['fields']['state']['label'] = 'Status';
/* Field: Registration: Runner Type */
$handler->display->display_options['fields']['field_runner_type']['id'] = 'field_runner_type';
$handler->display->display_options['fields']['field_runner_type']['table'] = 'field_data_field_runner_type';
$handler->display->display_options['fields']['field_runner_type']['field'] = 'field_runner_type';
/* Field: Registration: Registration type */
$handler->display->display_options['fields']['type']['id'] = 'type';
$handler->display->display_options['fields']['type']['table'] = 'registration';
$handler->display->display_options['fields']['type']['field'] = 'type';
/* Field: Profile: Gender */
$handler->display->display_options['fields']['field_gender']['id'] = 'field_gender';
$handler->display->display_options['fields']['field_gender']['table'] = 'field_data_field_gender';
$handler->display->display_options['fields']['field_gender']['field'] = 'field_gender';
$handler->display->display_options['fields']['field_gender']['relationship'] = 'profile';
/* Field: Registration: Medal Year */
$handler->display->display_options['fields']['field_medal_year']['id'] = 'field_medal_year';
$handler->display->display_options['fields']['field_medal_year']['table'] = 'field_data_field_medal_year';
$handler->display->display_options['fields']['field_medal_year']['field'] = 'field_medal_year';
$handler->display->display_options['defaults']['arguments'] = FALSE;
/* Contextual filter: Content: Title */
$handler->display->display_options['arguments']['title']['id'] = 'title';
$handler->display->display_options['arguments']['title']['table'] = 'node';
$handler->display->display_options['arguments']['title']['field'] = 'title';
$handler->display->display_options['arguments']['title']['relationship'] = 'registration_related_node';
$handler->display->display_options['arguments']['title']['default_argument_type'] = 'fixed';
$handler->display->display_options['arguments']['title']['summary']['number_of_records'] = '0';
$handler->display->display_options['arguments']['title']['summary']['format'] = 'default_summary';
$handler->display->display_options['arguments']['title']['summary_options']['items_per_page'] = '25';
$handler->display->display_options['arguments']['title']['limit'] = '0';
/* Contextual filter: Registration: Event Date (field_year) */
$handler->display->display_options['arguments']['field_year_value']['id'] = 'field_year_value';
$handler->display->display_options['arguments']['field_year_value']['table'] = 'field_data_field_year';
$handler->display->display_options['arguments']['field_year_value']['field'] = 'field_year_value';
$handler->display->display_options['arguments']['field_year_value']['default_action'] = 'default';
$handler->display->display_options['arguments']['field_year_value']['default_argument_type'] = 'php';
$handler->display->display_options['arguments']['field_year_value']['default_argument_options']['code'] = 'echo date("Y"); ';
$handler->display->display_options['arguments']['field_year_value']['summary']['number_of_records'] = '0';
$handler->display->display_options['arguments']['field_year_value']['summary']['format'] = 'default_summary';
$handler->display->display_options['arguments']['field_year_value']['summary_options']['items_per_page'] = '25';
$handler->display->display_options['arguments']['field_year_value']['limit'] = '0';
$handler->display->display_options['defaults']['filter_groups'] = FALSE;
$handler->display->display_options['defaults']['filters'] = FALSE;
/* Filter criterion: Registration: State entity */
$handler->display->display_options['filters']['state']['id'] = 'state';
$handler->display->display_options['filters']['state']['table'] = 'registration';
$handler->display->display_options['filters']['state']['field'] = 'state';
$handler->display->display_options['filters']['state']['value'] = array(
  'waitlist' => 'waitlist',
  'invited' => 'invited',
  'complete' => 'complete',
  'paid' => 'paid',
  'canceled' => 'canceled',
);
/* Filter criterion: Registration: Medal Year (field_medal_year) */
$handler->display->display_options['filters']['field_medal_year_value']['id'] = 'field_medal_year_value';
$handler->display->display_options['filters']['field_medal_year_value']['table'] = 'field_data_field_medal_year';
$handler->display->display_options['filters']['field_medal_year_value']['field'] = 'field_medal_year_value';
$handler->display->display_options['filters']['field_medal_year_value']['value'] = array(
  5 => '5',
  10 => '10',
  20 => '20',
);
$handler->display->display_options['path'] = 'admin/data_export/medalists.csv';
$handler->display->display_options['sitename_title'] = 0;

/* Display: Medicals Export */
$handler = $view->new_display('views_data_export', 'Medicals Export', 'views_data_export_6');
$handler->display->display_options['defaults']['title'] = FALSE;
$handler->display->display_options['title'] = 'Medicals Export';
$handler->display->display_options['display_description'] = 'Runner Export - medicals';
$handler->display->display_options['pager']['type'] = 'none';
$handler->display->display_options['pager']['options']['offset'] = '0';
$handler->display->display_options['style_plugin'] = 'views_data_export_csv';
$handler->display->display_options['defaults']['fields'] = FALSE;
/* Field: Global: View result counter */
$handler->display->display_options['fields']['counter']['id'] = 'counter';
$handler->display->display_options['fields']['counter']['table'] = 'views';
$handler->display->display_options['fields']['counter']['field'] = 'counter';
$handler->display->display_options['fields']['counter']['label'] = 'Counter';
$handler->display->display_options['fields']['counter']['counter_start'] = '1';
$handler->display->display_options['fields']['counter']['reverse'] = 0;
/* Field: Registration: Registration ID */
$handler->display->display_options['fields']['registration_id']['id'] = 'registration_id';
$handler->display->display_options['fields']['registration_id']['table'] = 'registration';
$handler->display->display_options['fields']['registration_id']['field'] = 'registration_id';
$handler->display->display_options['fields']['registration_id']['exclude'] = TRUE;
$handler->display->display_options['fields']['registration_id']['separator'] = '';
/* Field: Registration: User */
$handler->display->display_options['fields']['user_uid']['id'] = 'user_uid';
$handler->display->display_options['fields']['user_uid']['table'] = 'registration';
$handler->display->display_options['fields']['user_uid']['field'] = 'user_uid';
$handler->display->display_options['fields']['user_uid']['separator'] = '';
/* Field: Profile: Name &amp; Address - First name */
$handler->display->display_options['fields']['field_name_address_first_name']['id'] = 'field_name_address_first_name';
$handler->display->display_options['fields']['field_name_address_first_name']['table'] = 'field_data_field_name_address';
$handler->display->display_options['fields']['field_name_address_first_name']['field'] = 'field_name_address_first_name';
$handler->display->display_options['fields']['field_name_address_first_name']['relationship'] = 'profile';
$handler->display->display_options['fields']['field_name_address_first_name']['label'] = 'First name';
/* Field: Profile: Name &amp; Address - Last name */
$handler->display->display_options['fields']['field_name_address_last_name']['id'] = 'field_name_address_last_name';
$handler->display->display_options['fields']['field_name_address_last_name']['table'] = 'field_data_field_name_address';
$handler->display->display_options['fields']['field_name_address_last_name']['field'] = 'field_name_address_last_name';
$handler->display->display_options['fields']['field_name_address_last_name']['relationship'] = 'profile';
$handler->display->display_options['fields']['field_name_address_last_name']['label'] = 'Last name';
/* Field: Profile: Name &amp; Address - Locality (i.e. City) */
$handler->display->display_options['fields']['field_name_address_locality']['id'] = 'field_name_address_locality';
$handler->display->display_options['fields']['field_name_address_locality']['table'] = 'field_data_field_name_address';
$handler->display->display_options['fields']['field_name_address_locality']['field'] = 'field_name_address_locality';
$handler->display->display_options['fields']['field_name_address_locality']['relationship'] = 'profile';
$handler->display->display_options['fields']['field_name_address_locality']['label'] = 'City';
/* Field: Profile: Name &amp; Address - Country */
$handler->display->display_options['fields']['field_name_address_country']['id'] = 'field_name_address_country';
$handler->display->display_options['fields']['field_name_address_country']['table'] = 'field_data_field_name_address';
$handler->display->display_options['fields']['field_name_address_country']['field'] = 'field_name_address_country';
$handler->display->display_options['fields']['field_name_address_country']['relationship'] = 'profile';
$handler->display->display_options['fields']['field_name_address_country']['label'] = 'Country';
$handler->display->display_options['fields']['field_name_address_country']['display_name'] = 1;
/* Field: User: E-mail */
$handler->display->display_options['fields']['mail']['id'] = 'mail';
$handler->display->display_options['fields']['mail']['table'] = 'users';
$handler->display->display_options['fields']['mail']['field'] = 'mail';
$handler->display->display_options['fields']['mail']['relationship'] = 'user_uid';
/* Field: Registration: Registration type */
$handler->display->display_options['fields']['type']['id'] = 'type';
$handler->display->display_options['fields']['type']['table'] = 'registration';
$handler->display->display_options['fields']['type']['field'] = 'type';
/* Field: Profile: Gender */
$handler->display->display_options['fields']['field_gender']['id'] = 'field_gender';
$handler->display->display_options['fields']['field_gender']['table'] = 'field_data_field_gender';
$handler->display->display_options['fields']['field_gender']['field'] = 'field_gender';
$handler->display->display_options['fields']['field_gender']['relationship'] = 'profile';
/* Field: Registration: State entity */
$handler->display->display_options['fields']['state']['id'] = 'state';
$handler->display->display_options['fields']['state']['table'] = 'registration';
$handler->display->display_options['fields']['state']['field'] = 'state';
$handler->display->display_options['fields']['state']['label'] = 'Status';
/* Field: Profile: Medical Condition Details */
$handler->display->display_options['fields']['field_medical_condition_details']['id'] = 'field_medical_condition_details';
$handler->display->display_options['fields']['field_medical_condition_details']['table'] = 'field_data_field_medical_condition_details';
$handler->display->display_options['fields']['field_medical_condition_details']['field'] = 'field_medical_condition_details';
$handler->display->display_options['fields']['field_medical_condition_details']['relationship'] = 'profile';
$handler->display->display_options['defaults']['arguments'] = FALSE;
/* Contextual filter: Content: Title */
$handler->display->display_options['arguments']['title']['id'] = 'title';
$handler->display->display_options['arguments']['title']['table'] = 'node';
$handler->display->display_options['arguments']['title']['field'] = 'title';
$handler->display->display_options['arguments']['title']['relationship'] = 'registration_related_node';
$handler->display->display_options['arguments']['title']['default_argument_type'] = 'fixed';
$handler->display->display_options['arguments']['title']['summary']['number_of_records'] = '0';
$handler->display->display_options['arguments']['title']['summary']['format'] = 'default_summary';
$handler->display->display_options['arguments']['title']['summary_options']['items_per_page'] = '25';
$handler->display->display_options['arguments']['title']['limit'] = '0';
/* Contextual filter: Registration: Event Date (field_year) */
$handler->display->display_options['arguments']['field_year_value']['id'] = 'field_year_value';
$handler->display->display_options['arguments']['field_year_value']['table'] = 'field_data_field_year';
$handler->display->display_options['arguments']['field_year_value']['field'] = 'field_year_value';
$handler->display->display_options['arguments']['field_year_value']['default_action'] = 'default';
$handler->display->display_options['arguments']['field_year_value']['default_argument_type'] = 'php';
$handler->display->display_options['arguments']['field_year_value']['default_argument_options']['code'] = 'echo date("Y"); ';
$handler->display->display_options['arguments']['field_year_value']['summary']['number_of_records'] = '0';
$handler->display->display_options['arguments']['field_year_value']['summary']['format'] = 'default_summary';
$handler->display->display_options['arguments']['field_year_value']['summary_options']['items_per_page'] = '25';
$handler->display->display_options['arguments']['field_year_value']['limit'] = '0';
$handler->display->display_options['defaults']['filter_groups'] = FALSE;
$handler->display->display_options['defaults']['filters'] = FALSE;
/* Filter criterion: CurrentYear */
$handler->display->display_options['filters']['php']['id'] = 'php';
$handler->display->display_options['filters']['php']['table'] = 'views';
$handler->display->display_options['filters']['php']['field'] = 'php';
$handler->display->display_options['filters']['php']['ui_name'] = 'CurrentYear';
$handler->display->display_options['filters']['php']['group'] = 1;
$handler->display->display_options['filters']['php']['use_php_setup'] = 0;
$handler->display->display_options['filters']['php']['php_filter'] = '    $race_date = getdate(strtotime("first Saturday of December"));
    $race_year = $race_date[\'year\'];
    $reg_year = getdate($row->created)[\'year\'];
    if ($reg_year < $race_year ) {
        return TRUE; // Rows where this returns true are not displayed
    }
    else {
        return FALSE;
    }';
/* Filter criterion: Registration: State entity */
$handler->display->display_options['filters']['state']['id'] = 'state';
$handler->display->display_options['filters']['state']['table'] = 'registration';
$handler->display->display_options['filters']['state']['field'] = 'state';
$handler->display->display_options['filters']['state']['value'] = array(
  'waitlist' => 'waitlist',
  'invited' => 'invited',
  'complete' => 'complete',
  'paid' => 'paid',
  'canceled' => 'canceled',
);
$handler->display->display_options['filters']['state']['group'] = 1;
/* Filter criterion: Profile: Medical Condition Details (field_medical_condition_details) */
$handler->display->display_options['filters']['field_medical_condition_details_value']['id'] = 'field_medical_condition_details_value';
$handler->display->display_options['filters']['field_medical_condition_details_value']['table'] = 'field_data_field_medical_condition_details';
$handler->display->display_options['filters']['field_medical_condition_details_value']['field'] = 'field_medical_condition_details_value';
$handler->display->display_options['filters']['field_medical_condition_details_value']['relationship'] = 'profile';
$handler->display->display_options['filters']['field_medical_condition_details_value']['operator'] = 'not empty';
$handler->display->display_options['filters']['field_medical_condition_details_value']['group'] = 1;
$handler->display->display_options['path'] = 'admin/data_export/medicals.csv';
$handler->display->display_options['sitename_title'] = 0;

/* Display: Kepler Full Export */
$handler = $view->new_display('views_data_export', 'Kepler Full Export', 'views_data_export_7');
$handler->display->display_options['defaults']['title'] = FALSE;
$handler->display->display_options['title'] = 'Kepler Full Export';
$handler->display->display_options['pager']['type'] = 'none';
$handler->display->display_options['pager']['options']['offset'] = '0';
$handler->display->display_options['style_plugin'] = 'views_data_export_csv';
$handler->display->display_options['defaults']['relationships'] = FALSE;
/* Relationship: Registration: User */
$handler->display->display_options['relationships']['user_uid']['id'] = 'user_uid';
$handler->display->display_options['relationships']['user_uid']['table'] = 'registration';
$handler->display->display_options['relationships']['user_uid']['field'] = 'user_uid';
/* Relationship: User: Profile */
$handler->display->display_options['relationships']['profile']['id'] = 'profile';
$handler->display->display_options['relationships']['profile']['table'] = 'users';
$handler->display->display_options['relationships']['profile']['field'] = 'profile';
$handler->display->display_options['relationships']['profile']['relationship'] = 'user_uid';
$handler->display->display_options['relationships']['profile']['bundle_types'] = array(
  'main' => 'main',
);
/* Relationship: Registration: Registration to Node */
$handler->display->display_options['relationships']['registration_related_node']['id'] = 'registration_related_node';
$handler->display->display_options['relationships']['registration_related_node']['table'] = 'registration';
$handler->display->display_options['relationships']['registration_related_node']['field'] = 'registration_related_node';
/* Relationship: Race Numbers: Registration_ID */
$handler->display->display_options['relationships']['RegID']['id'] = 'RegID';
$handler->display->display_options['relationships']['RegID']['table'] = 'RaceNumbers';
$handler->display->display_options['relationships']['RegID']['field'] = 'RegID';
$handler->display->display_options['defaults']['fields'] = FALSE;
/* Field: Global: View result counter */
$handler->display->display_options['fields']['counter']['id'] = 'counter';
$handler->display->display_options['fields']['counter']['table'] = 'views';
$handler->display->display_options['fields']['counter']['field'] = 'counter';
$handler->display->display_options['fields']['counter']['label'] = 'Counter';
$handler->display->display_options['fields']['counter']['counter_start'] = '1';
$handler->display->display_options['fields']['counter']['reverse'] = 0;
/* Field: Race Numbers: Race Number */
$handler->display->display_options['fields']['racenum']['id'] = 'racenum';
$handler->display->display_options['fields']['racenum']['table'] = 'RaceNumbers';
$handler->display->display_options['fields']['racenum']['field'] = 'racenum';
$handler->display->display_options['fields']['racenum']['relationship'] = 'RegID';
/* Field: Registration: Event Date */
$handler->display->display_options['fields']['field_year']['id'] = 'field_year';
$handler->display->display_options['fields']['field_year']['table'] = 'field_data_field_year';
$handler->display->display_options['fields']['field_year']['field'] = 'field_year';
$handler->display->display_options['fields']['field_year']['settings'] = array(
  'format_type' => 'yearonly',
  'fromto' => 'both',
  'multiple_number' => '',
  'multiple_from' => '',
  'multiple_to' => '',
  'show_remaining_days' => 0,
);
/* Field: Registration: Event Title */
$handler->display->display_options['fields']['field_event_title']['id'] = 'field_event_title';
$handler->display->display_options['fields']['field_event_title']['table'] = 'field_data_field_event_title';
$handler->display->display_options['fields']['field_event_title']['field'] = 'field_event_title';
$handler->display->display_options['fields']['field_event_title']['label'] = 'Event';
/* Field: Registration: Registration ID */
$handler->display->display_options['fields']['registration_id']['id'] = 'registration_id';
$handler->display->display_options['fields']['registration_id']['table'] = 'registration';
$handler->display->display_options['fields']['registration_id']['field'] = 'registration_id';
$handler->display->display_options['fields']['registration_id']['separator'] = '';
/* Field: Registration: State entity */
$handler->display->display_options['fields']['state']['id'] = 'state';
$handler->display->display_options['fields']['state']['table'] = 'registration';
$handler->display->display_options['fields']['state']['field'] = 'state';
$handler->display->display_options['fields']['state']['label'] = 'Status';
/* Field: Registration: User */
$handler->display->display_options['fields']['user_uid']['id'] = 'user_uid';
$handler->display->display_options['fields']['user_uid']['table'] = 'registration';
$handler->display->display_options['fields']['user_uid']['field'] = 'user_uid';
$handler->display->display_options['fields']['user_uid']['separator'] = '';
/* Field: Profile: Gender */
$handler->display->display_options['fields']['field_gender']['id'] = 'field_gender';
$handler->display->display_options['fields']['field_gender']['table'] = 'field_data_field_gender';
$handler->display->display_options['fields']['field_gender']['field'] = 'field_gender';
$handler->display->display_options['fields']['field_gender']['relationship'] = 'profile';
/* Field: Profile: Name &amp; Address - First name */
$handler->display->display_options['fields']['field_name_address_first_name']['id'] = 'field_name_address_first_name';
$handler->display->display_options['fields']['field_name_address_first_name']['table'] = 'field_data_field_name_address';
$handler->display->display_options['fields']['field_name_address_first_name']['field'] = 'field_name_address_first_name';
$handler->display->display_options['fields']['field_name_address_first_name']['relationship'] = 'profile';
$handler->display->display_options['fields']['field_name_address_first_name']['label'] = 'First name';
$handler->display->display_options['fields']['field_name_address_first_name']['exclude'] = TRUE;
/* Field: Profile: Name &amp; Address - Last name */
$handler->display->display_options['fields']['field_name_address_last_name']['id'] = 'field_name_address_last_name';
$handler->display->display_options['fields']['field_name_address_last_name']['table'] = 'field_data_field_name_address';
$handler->display->display_options['fields']['field_name_address_last_name']['field'] = 'field_name_address_last_name';
$handler->display->display_options['fields']['field_name_address_last_name']['relationship'] = 'profile';
$handler->display->display_options['fields']['field_name_address_last_name']['label'] = 'Last name';
$handler->display->display_options['fields']['field_name_address_last_name']['exclude'] = TRUE;
/* Field: Global: PHP */
$handler->display->display_options['fields']['php']['id'] = 'php';
$handler->display->display_options['fields']['php']['table'] = 'views';
$handler->display->display_options['fields']['php']['field'] = 'php';
$handler->display->display_options['fields']['php']['label'] = 'First name';
$handler->display->display_options['fields']['php']['use_php_setup'] = 0;
$handler->display->display_options['fields']['php']['php_output'] = '<?php
$op = strtoupper($row->field_name_address_first_name);
print $op;
?>';
$handler->display->display_options['fields']['php']['use_php_click_sortable'] = '0';
$handler->display->display_options['fields']['php']['php_click_sortable'] = '';
/* Field: Global: PHP */
$handler->display->display_options['fields']['php_1']['id'] = 'php_1';
$handler->display->display_options['fields']['php_1']['table'] = 'views';
$handler->display->display_options['fields']['php_1']['field'] = 'php';
$handler->display->display_options['fields']['php_1']['label'] = 'Last name';
$handler->display->display_options['fields']['php_1']['use_php_setup'] = 0;
$handler->display->display_options['fields']['php_1']['php_output'] = '<?php
$op = strtoupper($row->field_name_address_last_name);
print $op;
?>';
$handler->display->display_options['fields']['php_1']['use_php_click_sortable'] = '0';
$handler->display->display_options['fields']['php_1']['php_click_sortable'] = '';
/* Field: Profile: Name &amp; Address - Thoroughfare (i.e. Street address) */
$handler->display->display_options['fields']['field_name_address_thoroughfare']['id'] = 'field_name_address_thoroughfare';
$handler->display->display_options['fields']['field_name_address_thoroughfare']['table'] = 'field_data_field_name_address';
$handler->display->display_options['fields']['field_name_address_thoroughfare']['field'] = 'field_name_address_thoroughfare';
$handler->display->display_options['fields']['field_name_address_thoroughfare']['relationship'] = 'profile';
$handler->display->display_options['fields']['field_name_address_thoroughfare']['label'] = 'Street address';
/* Field: Profile: Name &amp; Address - Administrative area (i.e. State / Province) */
$handler->display->display_options['fields']['field_name_address_administrative_area']['id'] = 'field_name_address_administrative_area';
$handler->display->display_options['fields']['field_name_address_administrative_area']['table'] = 'field_data_field_name_address';
$handler->display->display_options['fields']['field_name_address_administrative_area']['field'] = 'field_name_address_administrative_area';
$handler->display->display_options['fields']['field_name_address_administrative_area']['relationship'] = 'profile';
$handler->display->display_options['fields']['field_name_address_administrative_area']['label'] = 'State / Province';
$handler->display->display_options['fields']['field_name_address_administrative_area']['display_name'] = 1;
/* Field: Profile: Name &amp; Address - Locality (i.e. City) */
$handler->display->display_options['fields']['field_name_address_locality']['id'] = 'field_name_address_locality';
$handler->display->display_options['fields']['field_name_address_locality']['table'] = 'field_data_field_name_address';
$handler->display->display_options['fields']['field_name_address_locality']['field'] = 'field_name_address_locality';
$handler->display->display_options['fields']['field_name_address_locality']['relationship'] = 'profile';
$handler->display->display_options['fields']['field_name_address_locality']['label'] = 'City';
/* Field: Profile: Name &amp; Address - Postal code */
$handler->display->display_options['fields']['field_name_address_postal_code']['id'] = 'field_name_address_postal_code';
$handler->display->display_options['fields']['field_name_address_postal_code']['table'] = 'field_data_field_name_address';
$handler->display->display_options['fields']['field_name_address_postal_code']['field'] = 'field_name_address_postal_code';
$handler->display->display_options['fields']['field_name_address_postal_code']['relationship'] = 'profile';
$handler->display->display_options['fields']['field_name_address_postal_code']['label'] = 'Postal code';
/* Field: Profile: Name &amp; Address - Country */
$handler->display->display_options['fields']['field_name_address_country']['id'] = 'field_name_address_country';
$handler->display->display_options['fields']['field_name_address_country']['table'] = 'field_data_field_name_address';
$handler->display->display_options['fields']['field_name_address_country']['field'] = 'field_name_address_country';
$handler->display->display_options['fields']['field_name_address_country']['relationship'] = 'profile';
$handler->display->display_options['fields']['field_name_address_country']['label'] = 'Country';
$handler->display->display_options['fields']['field_name_address_country']['display_name'] = 1;
/* Field: Profile: Main Ph. */
$handler->display->display_options['fields']['field_home_ph_']['id'] = 'field_home_ph_';
$handler->display->display_options['fields']['field_home_ph_']['table'] = 'field_data_field_home_ph_';
$handler->display->display_options['fields']['field_home_ph_']['field'] = 'field_home_ph_';
$handler->display->display_options['fields']['field_home_ph_']['relationship'] = 'profile';
/* Field: User: E-mail */
$handler->display->display_options['fields']['mail']['id'] = 'mail';
$handler->display->display_options['fields']['mail']['table'] = 'users';
$handler->display->display_options['fields']['mail']['field'] = 'mail';
$handler->display->display_options['fields']['mail']['relationship'] = 'user_uid';
/* Field: Profile: DOB */
$handler->display->display_options['fields']['field_dob']['id'] = 'field_dob';
$handler->display->display_options['fields']['field_dob']['table'] = 'field_data_field_dob';
$handler->display->display_options['fields']['field_dob']['field'] = 'field_dob';
$handler->display->display_options['fields']['field_dob']['relationship'] = 'profile';
$handler->display->display_options['fields']['field_dob']['settings'] = array(
  'format_type' => 'nz_uk_date',
  'fromto' => 'both',
  'multiple_number' => '',
  'multiple_from' => '',
  'multiple_to' => '',
  'show_remaining_days' => 0,
);
/* Field: Registration: Runner Type */
$handler->display->display_options['fields']['field_runner_type']['id'] = 'field_runner_type';
$handler->display->display_options['fields']['field_runner_type']['table'] = 'field_data_field_runner_type';
$handler->display->display_options['fields']['field_runner_type']['field'] = 'field_runner_type';
/* Field: Registration: Registration type */
$handler->display->display_options['fields']['type']['id'] = 'type';
$handler->display->display_options['fields']['type']['table'] = 'registration';
$handler->display->display_options['fields']['type']['field'] = 'type';
/* Field: Registration: Rendered Registration */
$handler->display->display_options['fields']['rendered_entity']['id'] = 'rendered_entity';
$handler->display->display_options['fields']['rendered_entity']['table'] = 'views_entity_registration';
$handler->display->display_options['fields']['rendered_entity']['field'] = 'rendered_entity';
$handler->display->display_options['fields']['rendered_entity']['exclude'] = TRUE;
$handler->display->display_options['fields']['rendered_entity']['link_to_entity'] = 1;
$handler->display->display_options['fields']['rendered_entity']['view_mode'] = 'full';
$handler->display->display_options['fields']['rendered_entity']['bypass_access'] = 0;
/* Field: Profile: Medical Condition Details */
$handler->display->display_options['fields']['field_medical_condition_details']['id'] = 'field_medical_condition_details';
$handler->display->display_options['fields']['field_medical_condition_details']['table'] = 'field_data_field_medical_condition_details';
$handler->display->display_options['fields']['field_medical_condition_details']['field'] = 'field_medical_condition_details';
$handler->display->display_options['fields']['field_medical_condition_details']['relationship'] = 'profile';
$handler->display->display_options['fields']['field_medical_condition_details']['label'] = 'Medical Conditions';
/* Field: Registration: No of Prev events */
$handler->display->display_options['fields']['field_no_of_prev_events']['id'] = 'field_no_of_prev_events';
$handler->display->display_options['fields']['field_no_of_prev_events']['table'] = 'field_data_field_no_of_prev_events';
$handler->display->display_options['fields']['field_no_of_prev_events']['field'] = 'field_no_of_prev_events';
/* Field: Registration: Medal Year */
$handler->display->display_options['fields']['field_medal_year']['id'] = 'field_medal_year';
$handler->display->display_options['fields']['field_medal_year']['table'] = 'field_data_field_medal_year';
$handler->display->display_options['fields']['field_medal_year']['field'] = 'field_medal_year';
/* Field: Registration: Previous best result */
$handler->display->display_options['fields']['field_previous_best_time']['id'] = 'field_previous_best_time';
$handler->display->display_options['fields']['field_previous_best_time']['table'] = 'field_data_field_previous_best_time';
$handler->display->display_options['fields']['field_previous_best_time']['field'] = 'field_previous_best_time';
$handler->display->display_options['fields']['field_previous_best_time']['settings'] = array(
  'format_type' => 'timeonly',
  'fromto' => 'both',
  'multiple_number' => '',
  'multiple_from' => '',
  'multiple_to' => '',
  'show_remaining_days' => 0,
);
/* Field: Registration: Year of previous best result */
$handler->display->display_options['fields']['field_year_of_previous_best_resu']['id'] = 'field_year_of_previous_best_resu';
$handler->display->display_options['fields']['field_year_of_previous_best_resu']['table'] = 'field_data_field_year_of_previous_best_resu';
$handler->display->display_options['fields']['field_year_of_previous_best_resu']['field'] = 'field_year_of_previous_best_resu';
$handler->display->display_options['fields']['field_year_of_previous_best_resu']['settings'] = array(
  'format_type' => 'yearonly',
  'fromto' => 'both',
  'multiple_number' => '',
  'multiple_from' => '',
  'multiple_to' => '',
  'show_remaining_days' => 0,
);
/* Field: Registration: Est. Time this year */
$handler->display->display_options['fields']['field_est_time_this_year']['id'] = 'field_est_time_this_year';
$handler->display->display_options['fields']['field_est_time_this_year']['table'] = 'field_data_field_est_time_this_year';
$handler->display->display_options['fields']['field_est_time_this_year']['field'] = 'field_est_time_this_year';
$handler->display->display_options['fields']['field_est_time_this_year']['settings'] = array(
  'format_type' => 'timeonly',
  'fromto' => 'both',
  'multiple_number' => '',
  'multiple_from' => '',
  'multiple_to' => '',
  'show_remaining_days' => 0,
);
/* Field: Registration: Notes */
$handler->display->display_options['fields']['field_notes']['id'] = 'field_notes';
$handler->display->display_options['fields']['field_notes']['table'] = 'field_data_field_notes';
$handler->display->display_options['fields']['field_notes']['field'] = 'field_notes';
/* Field: Registration: Tags */
$handler->display->display_options['fields']['field_tags']['id'] = 'field_tags';
$handler->display->display_options['fields']['field_tags']['table'] = 'field_data_field_tags';
$handler->display->display_options['fields']['field_tags']['field'] = 'field_tags';
$handler->display->display_options['fields']['field_tags']['type'] = 'taxonomy_term_reference_plain';
$handler->display->display_options['fields']['field_tags']['delta_offset'] = '0';
/* Field: Profile: Running profile */
$handler->display->display_options['fields']['field_running_profile']['id'] = 'field_running_profile';
$handler->display->display_options['fields']['field_running_profile']['table'] = 'field_data_field_running_profile';
$handler->display->display_options['fields']['field_running_profile']['field'] = 'field_running_profile';
$handler->display->display_options['fields']['field_running_profile']['relationship'] = 'profile';
/* Field: Profile: Commentary */
$handler->display->display_options['fields']['field_commentary']['id'] = 'field_commentary';
$handler->display->display_options['fields']['field_commentary']['table'] = 'field_data_field_commentary';
$handler->display->display_options['fields']['field_commentary']['field'] = 'field_commentary';
$handler->display->display_options['fields']['field_commentary']['relationship'] = 'profile';
/* Field: Registration: Date updated */
$handler->display->display_options['fields']['updated']['id'] = 'updated';
$handler->display->display_options['fields']['updated']['table'] = 'registration';
$handler->display->display_options['fields']['updated']['field'] = 'updated';
$handler->display->display_options['fields']['updated']['date_format'] = 'short';
$handler->display->display_options['fields']['updated']['second_date_format'] = 'long';
$handler->display->display_options['defaults']['filter_groups'] = FALSE;
$handler->display->display_options['defaults']['filters'] = FALSE;
/* Filter criterion: CurrentYear */
$handler->display->display_options['filters']['php']['id'] = 'php';
$handler->display->display_options['filters']['php']['table'] = 'views';
$handler->display->display_options['filters']['php']['field'] = 'php';
$handler->display->display_options['filters']['php']['ui_name'] = 'CurrentYear';
$handler->display->display_options['filters']['php']['group'] = 1;
$handler->display->display_options['filters']['php']['use_php_setup'] = 0;
$handler->display->display_options['filters']['php']['php_filter'] = '    $race_date = getdate(strtotime("first Saturday of December"));
    $race_year = $race_date[\'year\'];
    $reg_year = getdate($row->created)[\'year\'];
    if ($reg_year < $race_year ) {
        return TRUE; // Rows where this returns true are not displayed
    }
    else {
        return FALSE;
    }';
/* Filter criterion: Registration: State entity */
$handler->display->display_options['filters']['state']['id'] = 'state';
$handler->display->display_options['filters']['state']['table'] = 'registration';
$handler->display->display_options['filters']['state']['field'] = 'state';
$handler->display->display_options['filters']['state']['value'] = array(
  'waitlist' => 'waitlist',
  'invited' => 'invited',
  'complete' => 'complete',
  'paid' => 'paid',
  'canceled' => 'canceled',
);
$handler->display->display_options['filters']['state']['group'] = 1;
/* Filter criterion: Registration: Registration type */
$handler->display->display_options['filters']['type']['id'] = 'type';
$handler->display->display_options['filters']['type']['table'] = 'registration';
$handler->display->display_options['filters']['type']['field'] = 'type';
$handler->display->display_options['filters']['type']['value'] = array(
  'keplerreg' => 'keplerreg',
);
$handler->display->display_options['filters']['type']['group'] = 1;
$handler->display->display_options['path'] = 'admin/data_export/kepler_full.csv';
$handler->display->display_options['sitename_title'] = 0;

/* Display: Grunt Full Export */
$handler = $view->new_display('views_data_export', 'Grunt Full Export', 'views_data_export_8');
$handler->display->display_options['defaults']['title'] = FALSE;
$handler->display->display_options['title'] = 'Grunt Full Export';
$handler->display->display_options['pager']['type'] = 'none';
$handler->display->display_options['pager']['options']['offset'] = '0';
$handler->display->display_options['style_plugin'] = 'views_data_export_csv';
$handler->display->display_options['defaults']['relationships'] = FALSE;
/* Relationship: Registration: User */
$handler->display->display_options['relationships']['user_uid']['id'] = 'user_uid';
$handler->display->display_options['relationships']['user_uid']['table'] = 'registration';
$handler->display->display_options['relationships']['user_uid']['field'] = 'user_uid';
/* Relationship: User: Profile */
$handler->display->display_options['relationships']['profile']['id'] = 'profile';
$handler->display->display_options['relationships']['profile']['table'] = 'users';
$handler->display->display_options['relationships']['profile']['field'] = 'profile';
$handler->display->display_options['relationships']['profile']['relationship'] = 'user_uid';
$handler->display->display_options['relationships']['profile']['bundle_types'] = array(
  'main' => 'main',
);
/* Relationship: Registration: Registration to Node */
$handler->display->display_options['relationships']['registration_related_node']['id'] = 'registration_related_node';
$handler->display->display_options['relationships']['registration_related_node']['table'] = 'registration';
$handler->display->display_options['relationships']['registration_related_node']['field'] = 'registration_related_node';
/* Relationship: Race Numbers: Registration_ID */
$handler->display->display_options['relationships']['RegID']['id'] = 'RegID';
$handler->display->display_options['relationships']['RegID']['table'] = 'RaceNumbers';
$handler->display->display_options['relationships']['RegID']['field'] = 'RegID';
$handler->display->display_options['defaults']['fields'] = FALSE;
/* Field: Global: View result counter */
$handler->display->display_options['fields']['counter']['id'] = 'counter';
$handler->display->display_options['fields']['counter']['table'] = 'views';
$handler->display->display_options['fields']['counter']['field'] = 'counter';
$handler->display->display_options['fields']['counter']['label'] = 'Counter';
$handler->display->display_options['fields']['counter']['counter_start'] = '1';
$handler->display->display_options['fields']['counter']['reverse'] = 0;
/* Field: Race Numbers: Race Number */
$handler->display->display_options['fields']['racenum']['id'] = 'racenum';
$handler->display->display_options['fields']['racenum']['table'] = 'RaceNumbers';
$handler->display->display_options['fields']['racenum']['field'] = 'racenum';
$handler->display->display_options['fields']['racenum']['relationship'] = 'RegID';
/* Field: Registration: Event Date */
$handler->display->display_options['fields']['field_year']['id'] = 'field_year';
$handler->display->display_options['fields']['field_year']['table'] = 'field_data_field_year';
$handler->display->display_options['fields']['field_year']['field'] = 'field_year';
$handler->display->display_options['fields']['field_year']['settings'] = array(
  'format_type' => 'yearonly',
  'fromto' => 'both',
  'multiple_number' => '',
  'multiple_from' => '',
  'multiple_to' => '',
  'show_remaining_days' => 0,
);
/* Field: Registration: Event Title */
$handler->display->display_options['fields']['field_event_title']['id'] = 'field_event_title';
$handler->display->display_options['fields']['field_event_title']['table'] = 'field_data_field_event_title';
$handler->display->display_options['fields']['field_event_title']['field'] = 'field_event_title';
$handler->display->display_options['fields']['field_event_title']['label'] = 'Event';
/* Field: Registration: Registration ID */
$handler->display->display_options['fields']['registration_id']['id'] = 'registration_id';
$handler->display->display_options['fields']['registration_id']['table'] = 'registration';
$handler->display->display_options['fields']['registration_id']['field'] = 'registration_id';
$handler->display->display_options['fields']['registration_id']['separator'] = '';
/* Field: Registration: State entity */
$handler->display->display_options['fields']['state']['id'] = 'state';
$handler->display->display_options['fields']['state']['table'] = 'registration';
$handler->display->display_options['fields']['state']['field'] = 'state';
$handler->display->display_options['fields']['state']['label'] = 'Status';
/* Field: Registration: User */
$handler->display->display_options['fields']['user_uid']['id'] = 'user_uid';
$handler->display->display_options['fields']['user_uid']['table'] = 'registration';
$handler->display->display_options['fields']['user_uid']['field'] = 'user_uid';
$handler->display->display_options['fields']['user_uid']['separator'] = '';
/* Field: Profile: Gender */
$handler->display->display_options['fields']['field_gender']['id'] = 'field_gender';
$handler->display->display_options['fields']['field_gender']['table'] = 'field_data_field_gender';
$handler->display->display_options['fields']['field_gender']['field'] = 'field_gender';
$handler->display->display_options['fields']['field_gender']['relationship'] = 'profile';
/* Field: Profile: Name &amp; Address - First name */
$handler->display->display_options['fields']['field_name_address_first_name']['id'] = 'field_name_address_first_name';
$handler->display->display_options['fields']['field_name_address_first_name']['table'] = 'field_data_field_name_address';
$handler->display->display_options['fields']['field_name_address_first_name']['field'] = 'field_name_address_first_name';
$handler->display->display_options['fields']['field_name_address_first_name']['relationship'] = 'profile';
$handler->display->display_options['fields']['field_name_address_first_name']['label'] = 'First name';
$handler->display->display_options['fields']['field_name_address_first_name']['exclude'] = TRUE;
/* Field: Profile: Name &amp; Address - Last name */
$handler->display->display_options['fields']['field_name_address_last_name']['id'] = 'field_name_address_last_name';
$handler->display->display_options['fields']['field_name_address_last_name']['table'] = 'field_data_field_name_address';
$handler->display->display_options['fields']['field_name_address_last_name']['field'] = 'field_name_address_last_name';
$handler->display->display_options['fields']['field_name_address_last_name']['relationship'] = 'profile';
$handler->display->display_options['fields']['field_name_address_last_name']['label'] = 'Last name';
$handler->display->display_options['fields']['field_name_address_last_name']['exclude'] = TRUE;
/* Field: Global: PHP */
$handler->display->display_options['fields']['php']['id'] = 'php';
$handler->display->display_options['fields']['php']['table'] = 'views';
$handler->display->display_options['fields']['php']['field'] = 'php';
$handler->display->display_options['fields']['php']['label'] = 'First name';
$handler->display->display_options['fields']['php']['use_php_setup'] = 0;
$handler->display->display_options['fields']['php']['php_output'] = '<?php
$op = strtoupper($row->field_name_address_first_name);
print $op;
?>';
$handler->display->display_options['fields']['php']['use_php_click_sortable'] = '0';
$handler->display->display_options['fields']['php']['php_click_sortable'] = '';
/* Field: Global: PHP */
$handler->display->display_options['fields']['php_1']['id'] = 'php_1';
$handler->display->display_options['fields']['php_1']['table'] = 'views';
$handler->display->display_options['fields']['php_1']['field'] = 'php';
$handler->display->display_options['fields']['php_1']['label'] = 'Last name';
$handler->display->display_options['fields']['php_1']['use_php_setup'] = 0;
$handler->display->display_options['fields']['php_1']['php_output'] = '<?php
$op = strtoupper($row->field_name_address_last_name);
print $op;
?>';
$handler->display->display_options['fields']['php_1']['use_php_click_sortable'] = '0';
$handler->display->display_options['fields']['php_1']['php_click_sortable'] = '';
/* Field: Profile: Name &amp; Address - Thoroughfare (i.e. Street address) */
$handler->display->display_options['fields']['field_name_address_thoroughfare']['id'] = 'field_name_address_thoroughfare';
$handler->display->display_options['fields']['field_name_address_thoroughfare']['table'] = 'field_data_field_name_address';
$handler->display->display_options['fields']['field_name_address_thoroughfare']['field'] = 'field_name_address_thoroughfare';
$handler->display->display_options['fields']['field_name_address_thoroughfare']['relationship'] = 'profile';
$handler->display->display_options['fields']['field_name_address_thoroughfare']['label'] = 'Street address';
/* Field: Profile: Name &amp; Address - Administrative area (i.e. State / Province) */
$handler->display->display_options['fields']['field_name_address_administrative_area']['id'] = 'field_name_address_administrative_area';
$handler->display->display_options['fields']['field_name_address_administrative_area']['table'] = 'field_data_field_name_address';
$handler->display->display_options['fields']['field_name_address_administrative_area']['field'] = 'field_name_address_administrative_area';
$handler->display->display_options['fields']['field_name_address_administrative_area']['relationship'] = 'profile';
$handler->display->display_options['fields']['field_name_address_administrative_area']['label'] = 'State / Province';
$handler->display->display_options['fields']['field_name_address_administrative_area']['display_name'] = 1;
/* Field: Profile: Name &amp; Address - Locality (i.e. City) */
$handler->display->display_options['fields']['field_name_address_locality']['id'] = 'field_name_address_locality';
$handler->display->display_options['fields']['field_name_address_locality']['table'] = 'field_data_field_name_address';
$handler->display->display_options['fields']['field_name_address_locality']['field'] = 'field_name_address_locality';
$handler->display->display_options['fields']['field_name_address_locality']['relationship'] = 'profile';
$handler->display->display_options['fields']['field_name_address_locality']['label'] = 'City';
/* Field: Profile: Name &amp; Address - Postal code */
$handler->display->display_options['fields']['field_name_address_postal_code']['id'] = 'field_name_address_postal_code';
$handler->display->display_options['fields']['field_name_address_postal_code']['table'] = 'field_data_field_name_address';
$handler->display->display_options['fields']['field_name_address_postal_code']['field'] = 'field_name_address_postal_code';
$handler->display->display_options['fields']['field_name_address_postal_code']['relationship'] = 'profile';
$handler->display->display_options['fields']['field_name_address_postal_code']['label'] = 'Postal code';
/* Field: Profile: Name &amp; Address - Country */
$handler->display->display_options['fields']['field_name_address_country']['id'] = 'field_name_address_country';
$handler->display->display_options['fields']['field_name_address_country']['table'] = 'field_data_field_name_address';
$handler->display->display_options['fields']['field_name_address_country']['field'] = 'field_name_address_country';
$handler->display->display_options['fields']['field_name_address_country']['relationship'] = 'profile';
$handler->display->display_options['fields']['field_name_address_country']['label'] = 'Country';
$handler->display->display_options['fields']['field_name_address_country']['display_name'] = 1;
/* Field: Profile: Main Ph. */
$handler->display->display_options['fields']['field_home_ph_']['id'] = 'field_home_ph_';
$handler->display->display_options['fields']['field_home_ph_']['table'] = 'field_data_field_home_ph_';
$handler->display->display_options['fields']['field_home_ph_']['field'] = 'field_home_ph_';
$handler->display->display_options['fields']['field_home_ph_']['relationship'] = 'profile';
/* Field: User: E-mail */
$handler->display->display_options['fields']['mail']['id'] = 'mail';
$handler->display->display_options['fields']['mail']['table'] = 'users';
$handler->display->display_options['fields']['mail']['field'] = 'mail';
$handler->display->display_options['fields']['mail']['relationship'] = 'user_uid';
/* Field: Profile: DOB */
$handler->display->display_options['fields']['field_dob']['id'] = 'field_dob';
$handler->display->display_options['fields']['field_dob']['table'] = 'field_data_field_dob';
$handler->display->display_options['fields']['field_dob']['field'] = 'field_dob';
$handler->display->display_options['fields']['field_dob']['relationship'] = 'profile';
$handler->display->display_options['fields']['field_dob']['settings'] = array(
  'format_type' => 'nz_uk_date',
  'fromto' => 'both',
  'multiple_number' => '',
  'multiple_from' => '',
  'multiple_to' => '',
  'show_remaining_days' => 0,
);
/* Field: Registration: Runner Type */
$handler->display->display_options['fields']['field_runner_type']['id'] = 'field_runner_type';
$handler->display->display_options['fields']['field_runner_type']['table'] = 'field_data_field_runner_type';
$handler->display->display_options['fields']['field_runner_type']['field'] = 'field_runner_type';
/* Field: Registration: Registration type */
$handler->display->display_options['fields']['type']['id'] = 'type';
$handler->display->display_options['fields']['type']['table'] = 'registration';
$handler->display->display_options['fields']['type']['field'] = 'type';
/* Field: Registration: Rendered Registration */
$handler->display->display_options['fields']['rendered_entity']['id'] = 'rendered_entity';
$handler->display->display_options['fields']['rendered_entity']['table'] = 'views_entity_registration';
$handler->display->display_options['fields']['rendered_entity']['field'] = 'rendered_entity';
$handler->display->display_options['fields']['rendered_entity']['exclude'] = TRUE;
$handler->display->display_options['fields']['rendered_entity']['link_to_entity'] = 1;
$handler->display->display_options['fields']['rendered_entity']['view_mode'] = 'full';
$handler->display->display_options['fields']['rendered_entity']['bypass_access'] = 0;
/* Field: Profile: Medical Condition Details */
$handler->display->display_options['fields']['field_medical_condition_details']['id'] = 'field_medical_condition_details';
$handler->display->display_options['fields']['field_medical_condition_details']['table'] = 'field_data_field_medical_condition_details';
$handler->display->display_options['fields']['field_medical_condition_details']['field'] = 'field_medical_condition_details';
$handler->display->display_options['fields']['field_medical_condition_details']['relationship'] = 'profile';
$handler->display->display_options['fields']['field_medical_condition_details']['label'] = 'Medical Conditions';
/* Field: Registration: No of Prev events */
$handler->display->display_options['fields']['field_no_of_prev_events']['id'] = 'field_no_of_prev_events';
$handler->display->display_options['fields']['field_no_of_prev_events']['table'] = 'field_data_field_no_of_prev_events';
$handler->display->display_options['fields']['field_no_of_prev_events']['field'] = 'field_no_of_prev_events';
/* Field: Registration: Medal Year */
$handler->display->display_options['fields']['field_medal_year']['id'] = 'field_medal_year';
$handler->display->display_options['fields']['field_medal_year']['table'] = 'field_data_field_medal_year';
$handler->display->display_options['fields']['field_medal_year']['field'] = 'field_medal_year';
/* Field: Registration: Previous best result */
$handler->display->display_options['fields']['field_previous_best_time']['id'] = 'field_previous_best_time';
$handler->display->display_options['fields']['field_previous_best_time']['table'] = 'field_data_field_previous_best_time';
$handler->display->display_options['fields']['field_previous_best_time']['field'] = 'field_previous_best_time';
$handler->display->display_options['fields']['field_previous_best_time']['settings'] = array(
  'format_type' => 'timeonly',
  'fromto' => 'both',
  'multiple_number' => '',
  'multiple_from' => '',
  'multiple_to' => '',
  'show_remaining_days' => 0,
);
/* Field: Registration: Year of previous best result */
$handler->display->display_options['fields']['field_year_of_previous_best_resu']['id'] = 'field_year_of_previous_best_resu';
$handler->display->display_options['fields']['field_year_of_previous_best_resu']['table'] = 'field_data_field_year_of_previous_best_resu';
$handler->display->display_options['fields']['field_year_of_previous_best_resu']['field'] = 'field_year_of_previous_best_resu';
$handler->display->display_options['fields']['field_year_of_previous_best_resu']['settings'] = array(
  'format_type' => 'yearonly',
  'fromto' => 'both',
  'multiple_number' => '',
  'multiple_from' => '',
  'multiple_to' => '',
  'show_remaining_days' => 0,
);
/* Field: Registration: Est. Time this year */
$handler->display->display_options['fields']['field_est_time_this_year']['id'] = 'field_est_time_this_year';
$handler->display->display_options['fields']['field_est_time_this_year']['table'] = 'field_data_field_est_time_this_year';
$handler->display->display_options['fields']['field_est_time_this_year']['field'] = 'field_est_time_this_year';
$handler->display->display_options['fields']['field_est_time_this_year']['settings'] = array(
  'format_type' => 'timeonly',
  'fromto' => 'both',
  'multiple_number' => '',
  'multiple_from' => '',
  'multiple_to' => '',
  'show_remaining_days' => 0,
);
/* Field: Registration: Notes */
$handler->display->display_options['fields']['field_notes']['id'] = 'field_notes';
$handler->display->display_options['fields']['field_notes']['table'] = 'field_data_field_notes';
$handler->display->display_options['fields']['field_notes']['field'] = 'field_notes';
/* Field: Registration: Tags */
$handler->display->display_options['fields']['field_tags']['id'] = 'field_tags';
$handler->display->display_options['fields']['field_tags']['table'] = 'field_data_field_tags';
$handler->display->display_options['fields']['field_tags']['field'] = 'field_tags';
$handler->display->display_options['fields']['field_tags']['type'] = 'taxonomy_term_reference_plain';
$handler->display->display_options['fields']['field_tags']['delta_offset'] = '0';
/* Field: Profile: Running profile */
$handler->display->display_options['fields']['field_running_profile']['id'] = 'field_running_profile';
$handler->display->display_options['fields']['field_running_profile']['table'] = 'field_data_field_running_profile';
$handler->display->display_options['fields']['field_running_profile']['field'] = 'field_running_profile';
$handler->display->display_options['fields']['field_running_profile']['relationship'] = 'profile';
/* Field: Profile: Commentary */
$handler->display->display_options['fields']['field_commentary']['id'] = 'field_commentary';
$handler->display->display_options['fields']['field_commentary']['table'] = 'field_data_field_commentary';
$handler->display->display_options['fields']['field_commentary']['field'] = 'field_commentary';
$handler->display->display_options['fields']['field_commentary']['relationship'] = 'profile';
/* Field: Registration: Date updated */
$handler->display->display_options['fields']['updated']['id'] = 'updated';
$handler->display->display_options['fields']['updated']['table'] = 'registration';
$handler->display->display_options['fields']['updated']['field'] = 'updated';
$handler->display->display_options['fields']['updated']['date_format'] = 'short';
$handler->display->display_options['fields']['updated']['second_date_format'] = 'long';
$handler->display->display_options['defaults']['filter_groups'] = FALSE;
$handler->display->display_options['defaults']['filters'] = FALSE;
/* Filter criterion: Registration: State entity */
$handler->display->display_options['filters']['state']['id'] = 'state';
$handler->display->display_options['filters']['state']['table'] = 'registration';
$handler->display->display_options['filters']['state']['field'] = 'state';
$handler->display->display_options['filters']['state']['value'] = array(
  'waitlist' => 'waitlist',
  'invited' => 'invited',
  'complete' => 'complete',
  'paid' => 'paid',
  'canceled' => 'canceled',
);
/* Filter criterion: Registration: Registration type */
$handler->display->display_options['filters']['type']['id'] = 'type';
$handler->display->display_options['filters']['type']['table'] = 'registration';
$handler->display->display_options['filters']['type']['field'] = 'type';
$handler->display->display_options['filters']['type']['value'] = array(
  'gruntreg' => 'gruntreg',
);
/* Filter criterion: CurrentYear */
$handler->display->display_options['filters']['php']['id'] = 'php';
$handler->display->display_options['filters']['php']['table'] = 'views';
$handler->display->display_options['filters']['php']['field'] = 'php';
$handler->display->display_options['filters']['php']['ui_name'] = 'CurrentYear';
$handler->display->display_options['filters']['php']['use_php_setup'] = 0;
$handler->display->display_options['filters']['php']['php_filter'] = '    $race_date = getdate(strtotime("first Saturday of December"));
    $race_year = $race_date[\'year\'];
    $reg_year = getdate($row->created)[\'year\'];
    if ($reg_year < $race_year ) {
        return TRUE; // Rows where this returns true are not displayed
    }
    else {
        return FALSE;
    }';
$handler->display->display_options['path'] = 'admin/data_export/grunt_full.csv';
$handler->display->display_options['sitename_title'] = 0;

/* Display: Invalid DoB */
$handler = $view->new_display('views_data_export', 'Invalid DoB', 'views_data_export_9');
$handler->display->display_options['defaults']['title'] = FALSE;
$handler->display->display_options['title'] = 'Medicals Export';
$handler->display->display_options['display_description'] = 'Runner Export - invalid age';
$handler->display->display_options['pager']['type'] = 'none';
$handler->display->display_options['pager']['options']['offset'] = '0';
$handler->display->display_options['style_plugin'] = 'views_data_export_csv';
$handler->display->display_options['defaults']['fields'] = FALSE;
/* Field: Global: View result counter */
$handler->display->display_options['fields']['counter']['id'] = 'counter';
$handler->display->display_options['fields']['counter']['table'] = 'views';
$handler->display->display_options['fields']['counter']['field'] = 'counter';
$handler->display->display_options['fields']['counter']['label'] = 'Counter';
$handler->display->display_options['fields']['counter']['counter_start'] = '1';
$handler->display->display_options['fields']['counter']['reverse'] = 0;
/* Field: Registration: Registration ID */
$handler->display->display_options['fields']['registration_id']['id'] = 'registration_id';
$handler->display->display_options['fields']['registration_id']['table'] = 'registration';
$handler->display->display_options['fields']['registration_id']['field'] = 'registration_id';
$handler->display->display_options['fields']['registration_id']['exclude'] = TRUE;
$handler->display->display_options['fields']['registration_id']['separator'] = '';
/* Field: Registration: User */
$handler->display->display_options['fields']['user_uid']['id'] = 'user_uid';
$handler->display->display_options['fields']['user_uid']['table'] = 'registration';
$handler->display->display_options['fields']['user_uid']['field'] = 'user_uid';
$handler->display->display_options['fields']['user_uid']['separator'] = '';
/* Field: Profile: Name &amp; Address - First name */
$handler->display->display_options['fields']['field_name_address_first_name']['id'] = 'field_name_address_first_name';
$handler->display->display_options['fields']['field_name_address_first_name']['table'] = 'field_data_field_name_address';
$handler->display->display_options['fields']['field_name_address_first_name']['field'] = 'field_name_address_first_name';
$handler->display->display_options['fields']['field_name_address_first_name']['relationship'] = 'profile';
$handler->display->display_options['fields']['field_name_address_first_name']['label'] = 'First name';
/* Field: Profile: Name &amp; Address - Last name */
$handler->display->display_options['fields']['field_name_address_last_name']['id'] = 'field_name_address_last_name';
$handler->display->display_options['fields']['field_name_address_last_name']['table'] = 'field_data_field_name_address';
$handler->display->display_options['fields']['field_name_address_last_name']['field'] = 'field_name_address_last_name';
$handler->display->display_options['fields']['field_name_address_last_name']['relationship'] = 'profile';
$handler->display->display_options['fields']['field_name_address_last_name']['label'] = 'Last name';
/* Field: Profile: Name &amp; Address - Locality (i.e. City) */
$handler->display->display_options['fields']['field_name_address_locality']['id'] = 'field_name_address_locality';
$handler->display->display_options['fields']['field_name_address_locality']['table'] = 'field_data_field_name_address';
$handler->display->display_options['fields']['field_name_address_locality']['field'] = 'field_name_address_locality';
$handler->display->display_options['fields']['field_name_address_locality']['relationship'] = 'profile';
$handler->display->display_options['fields']['field_name_address_locality']['label'] = 'City';
/* Field: Profile: Name &amp; Address - Country */
$handler->display->display_options['fields']['field_name_address_country']['id'] = 'field_name_address_country';
$handler->display->display_options['fields']['field_name_address_country']['table'] = 'field_data_field_name_address';
$handler->display->display_options['fields']['field_name_address_country']['field'] = 'field_name_address_country';
$handler->display->display_options['fields']['field_name_address_country']['relationship'] = 'profile';
$handler->display->display_options['fields']['field_name_address_country']['label'] = 'Country';
$handler->display->display_options['fields']['field_name_address_country']['display_name'] = 1;
/* Field: User: E-mail */
$handler->display->display_options['fields']['mail']['id'] = 'mail';
$handler->display->display_options['fields']['mail']['table'] = 'users';
$handler->display->display_options['fields']['mail']['field'] = 'mail';
$handler->display->display_options['fields']['mail']['relationship'] = 'user_uid';
/* Field: Registration: Registration type */
$handler->display->display_options['fields']['type']['id'] = 'type';
$handler->display->display_options['fields']['type']['table'] = 'registration';
$handler->display->display_options['fields']['type']['field'] = 'type';
/* Field: Profile: Gender */
$handler->display->display_options['fields']['field_gender']['id'] = 'field_gender';
$handler->display->display_options['fields']['field_gender']['table'] = 'field_data_field_gender';
$handler->display->display_options['fields']['field_gender']['field'] = 'field_gender';
$handler->display->display_options['fields']['field_gender']['relationship'] = 'profile';
/* Field: Registration: State entity */
$handler->display->display_options['fields']['state']['id'] = 'state';
$handler->display->display_options['fields']['state']['table'] = 'registration';
$handler->display->display_options['fields']['state']['field'] = 'state';
$handler->display->display_options['fields']['state']['label'] = 'Status';
/* Field: Profile: DOB */
$handler->display->display_options['fields']['field_dob']['id'] = 'field_dob';
$handler->display->display_options['fields']['field_dob']['table'] = 'field_data_field_dob';
$handler->display->display_options['fields']['field_dob']['field'] = 'field_dob';
$handler->display->display_options['fields']['field_dob']['relationship'] = 'profile';
$handler->display->display_options['fields']['field_dob']['settings'] = array(
  'format_type' => 'nz_uk_date',
  'fromto' => 'both',
  'multiple_number' => '',
  'multiple_from' => '',
  'multiple_to' => '',
  'show_remaining_days' => 0,
);
$handler->display->display_options['defaults']['arguments'] = FALSE;
/* Contextual filter: Content: Title */
$handler->display->display_options['arguments']['title']['id'] = 'title';
$handler->display->display_options['arguments']['title']['table'] = 'node';
$handler->display->display_options['arguments']['title']['field'] = 'title';
$handler->display->display_options['arguments']['title']['relationship'] = 'registration_related_node';
$handler->display->display_options['arguments']['title']['default_argument_type'] = 'fixed';
$handler->display->display_options['arguments']['title']['summary']['number_of_records'] = '0';
$handler->display->display_options['arguments']['title']['summary']['format'] = 'default_summary';
$handler->display->display_options['arguments']['title']['summary_options']['items_per_page'] = '25';
$handler->display->display_options['arguments']['title']['limit'] = '0';
/* Contextual filter: Registration: Event Date (field_year) */
$handler->display->display_options['arguments']['field_year_value']['id'] = 'field_year_value';
$handler->display->display_options['arguments']['field_year_value']['table'] = 'field_data_field_year';
$handler->display->display_options['arguments']['field_year_value']['field'] = 'field_year_value';
$handler->display->display_options['arguments']['field_year_value']['default_action'] = 'default';
$handler->display->display_options['arguments']['field_year_value']['default_argument_type'] = 'php';
$handler->display->display_options['arguments']['field_year_value']['default_argument_options']['code'] = 'echo date("Y"); ';
$handler->display->display_options['arguments']['field_year_value']['summary']['number_of_records'] = '0';
$handler->display->display_options['arguments']['field_year_value']['summary']['format'] = 'default_summary';
$handler->display->display_options['arguments']['field_year_value']['summary_options']['items_per_page'] = '25';
$handler->display->display_options['arguments']['field_year_value']['limit'] = '0';
$handler->display->display_options['defaults']['filter_groups'] = FALSE;
$handler->display->display_options['defaults']['filters'] = FALSE;
/* Filter criterion: Registration: State entity */
$handler->display->display_options['filters']['state']['id'] = 'state';
$handler->display->display_options['filters']['state']['table'] = 'registration';
$handler->display->display_options['filters']['state']['field'] = 'state';
$handler->display->display_options['filters']['state']['value'] = array(
  'waitlist' => 'waitlist',
  'invited' => 'invited',
  'complete' => 'complete',
  'paid' => 'paid',
  'canceled' => 'canceled',
);
/* Filter criterion: Profile: DOB (field_dob) */
$handler->display->display_options['filters']['field_dob_value']['id'] = 'field_dob_value';
$handler->display->display_options['filters']['field_dob_value']['table'] = 'field_data_field_dob';
$handler->display->display_options['filters']['field_dob_value']['field'] = 'field_dob_value';
$handler->display->display_options['filters']['field_dob_value']['relationship'] = 'profile';
$handler->display->display_options['filters']['field_dob_value']['operator'] = 'regular_expression';
$handler->display->display_options['filters']['field_dob_value']['exposed'] = TRUE;
$handler->display->display_options['filters']['field_dob_value']['expose']['operator_id'] = 'field_dob_value_op';
$handler->display->display_options['filters']['field_dob_value']['expose']['label'] = 'DOB (field_dob)';
$handler->display->display_options['filters']['field_dob_value']['expose']['operator'] = 'field_dob_value_op';
$handler->display->display_options['filters']['field_dob_value']['expose']['identifier'] = 'field_dob_value';
$handler->display->display_options['filters']['field_dob_value']['expose']['remember_roles'] = array(
  2 => '2',
  1 => 0,
  3 => 0,
  4 => 0,
  5 => 0,
  6 => 0,
);
$handler->display->display_options['path'] = 'admin/data_export/invalidage.csv';
$handler->display->display_options['sitename_title'] = 0;

/* Display: ActiveTiming Kepler Export */
$handler = $view->new_display('views_data_export', 'ActiveTiming Kepler Export', 'views_data_export_10');
$handler->display->display_options['defaults']['title'] = FALSE;
$handler->display->display_options['title'] = 'ActiveTiming Kepler Export';
$handler->display->display_options['pager']['type'] = 'none';
$handler->display->display_options['pager']['options']['offset'] = '0';
$handler->display->display_options['style_plugin'] = 'views_data_export_csv';
$handler->display->display_options['defaults']['relationships'] = FALSE;
/* Relationship: Registration: User */
$handler->display->display_options['relationships']['user_uid']['id'] = 'user_uid';
$handler->display->display_options['relationships']['user_uid']['table'] = 'registration';
$handler->display->display_options['relationships']['user_uid']['field'] = 'user_uid';
/* Relationship: User: Profile */
$handler->display->display_options['relationships']['profile']['id'] = 'profile';
$handler->display->display_options['relationships']['profile']['table'] = 'users';
$handler->display->display_options['relationships']['profile']['field'] = 'profile';
$handler->display->display_options['relationships']['profile']['relationship'] = 'user_uid';
$handler->display->display_options['relationships']['profile']['bundle_types'] = array(
  'main' => 'main',
);
/* Relationship: Registration: Registration to Node */
$handler->display->display_options['relationships']['registration_related_node']['id'] = 'registration_related_node';
$handler->display->display_options['relationships']['registration_related_node']['table'] = 'registration';
$handler->display->display_options['relationships']['registration_related_node']['field'] = 'registration_related_node';
/* Relationship: Race Numbers: Registration_ID */
$handler->display->display_options['relationships']['RegID']['id'] = 'RegID';
$handler->display->display_options['relationships']['RegID']['table'] = 'RaceNumbers';
$handler->display->display_options['relationships']['RegID']['field'] = 'RegID';
$handler->display->display_options['defaults']['fields'] = FALSE;
/* Field: Global: View result counter */
$handler->display->display_options['fields']['counter']['id'] = 'counter';
$handler->display->display_options['fields']['counter']['table'] = 'views';
$handler->display->display_options['fields']['counter']['field'] = 'counter';
$handler->display->display_options['fields']['counter']['label'] = '';
$handler->display->display_options['fields']['counter']['exclude'] = TRUE;
$handler->display->display_options['fields']['counter']['element_label_colon'] = FALSE;
$handler->display->display_options['fields']['counter']['counter_start'] = '1';
$handler->display->display_options['fields']['counter']['reverse'] = 0;
/* Field: Race Numbers: Race Number */
$handler->display->display_options['fields']['racenum']['id'] = 'racenum';
$handler->display->display_options['fields']['racenum']['table'] = 'RaceNumbers';
$handler->display->display_options['fields']['racenum']['field'] = 'racenum';
$handler->display->display_options['fields']['racenum']['relationship'] = 'RegID';
/* Field: Registration: Event Date */
$handler->display->display_options['fields']['field_year']['id'] = 'field_year';
$handler->display->display_options['fields']['field_year']['table'] = 'field_data_field_year';
$handler->display->display_options['fields']['field_year']['field'] = 'field_year';
$handler->display->display_options['fields']['field_year']['settings'] = array(
  'format_type' => 'yearonly',
  'fromto' => 'both',
  'multiple_number' => '',
  'multiple_from' => '',
  'multiple_to' => '',
  'show_remaining_days' => 0,
);
/* Field: Registration: Event Title */
$handler->display->display_options['fields']['field_event_title']['id'] = 'field_event_title';
$handler->display->display_options['fields']['field_event_title']['table'] = 'field_data_field_event_title';
$handler->display->display_options['fields']['field_event_title']['field'] = 'field_event_title';
$handler->display->display_options['fields']['field_event_title']['label'] = 'Event';
/* Field: Registration: Registration ID */
$handler->display->display_options['fields']['registration_id']['id'] = 'registration_id';
$handler->display->display_options['fields']['registration_id']['table'] = 'registration';
$handler->display->display_options['fields']['registration_id']['field'] = 'registration_id';
$handler->display->display_options['fields']['registration_id']['separator'] = '';
/* Field: Registration: State entity */
$handler->display->display_options['fields']['state']['id'] = 'state';
$handler->display->display_options['fields']['state']['table'] = 'registration';
$handler->display->display_options['fields']['state']['field'] = 'state';
$handler->display->display_options['fields']['state']['label'] = 'Status';
/* Field: Registration: User */
$handler->display->display_options['fields']['user_uid']['id'] = 'user_uid';
$handler->display->display_options['fields']['user_uid']['table'] = 'registration';
$handler->display->display_options['fields']['user_uid']['field'] = 'user_uid';
$handler->display->display_options['fields']['user_uid']['separator'] = '';
/* Field: Profile: Gender */
$handler->display->display_options['fields']['field_gender']['id'] = 'field_gender';
$handler->display->display_options['fields']['field_gender']['table'] = 'field_data_field_gender';
$handler->display->display_options['fields']['field_gender']['field'] = 'field_gender';
$handler->display->display_options['fields']['field_gender']['relationship'] = 'profile';
/* Field: Profile: Name &amp; Address - First name */
$handler->display->display_options['fields']['field_name_address_first_name']['id'] = 'field_name_address_first_name';
$handler->display->display_options['fields']['field_name_address_first_name']['table'] = 'field_data_field_name_address';
$handler->display->display_options['fields']['field_name_address_first_name']['field'] = 'field_name_address_first_name';
$handler->display->display_options['fields']['field_name_address_first_name']['relationship'] = 'profile';
$handler->display->display_options['fields']['field_name_address_first_name']['label'] = 'First name';
$handler->display->display_options['fields']['field_name_address_first_name']['exclude'] = TRUE;
/* Field: Profile: Name &amp; Address - Last name */
$handler->display->display_options['fields']['field_name_address_last_name']['id'] = 'field_name_address_last_name';
$handler->display->display_options['fields']['field_name_address_last_name']['table'] = 'field_data_field_name_address';
$handler->display->display_options['fields']['field_name_address_last_name']['field'] = 'field_name_address_last_name';
$handler->display->display_options['fields']['field_name_address_last_name']['relationship'] = 'profile';
$handler->display->display_options['fields']['field_name_address_last_name']['label'] = 'Last name';
$handler->display->display_options['fields']['field_name_address_last_name']['exclude'] = TRUE;
/* Field: Global: PHP */
$handler->display->display_options['fields']['php']['id'] = 'php';
$handler->display->display_options['fields']['php']['table'] = 'views';
$handler->display->display_options['fields']['php']['field'] = 'php';
$handler->display->display_options['fields']['php']['label'] = 'First name';
$handler->display->display_options['fields']['php']['use_php_setup'] = 0;
$handler->display->display_options['fields']['php']['php_output'] = '<?php
$op = strtoupper($row->field_name_address_first_name);
print $op;
?>';
$handler->display->display_options['fields']['php']['use_php_click_sortable'] = '0';
$handler->display->display_options['fields']['php']['php_click_sortable'] = '';
/* Field: Global: PHP */
$handler->display->display_options['fields']['php_1']['id'] = 'php_1';
$handler->display->display_options['fields']['php_1']['table'] = 'views';
$handler->display->display_options['fields']['php_1']['field'] = 'php';
$handler->display->display_options['fields']['php_1']['label'] = 'Last name';
$handler->display->display_options['fields']['php_1']['use_php_setup'] = 0;
$handler->display->display_options['fields']['php_1']['php_output'] = '<?php
$op = strtoupper($row->field_name_address_last_name);
print $op;
?>';
$handler->display->display_options['fields']['php_1']['use_php_click_sortable'] = '0';
$handler->display->display_options['fields']['php_1']['php_click_sortable'] = '';
/* Field: Profile: Name &amp; Address - Thoroughfare (i.e. Street address) */
$handler->display->display_options['fields']['field_name_address_thoroughfare']['id'] = 'field_name_address_thoroughfare';
$handler->display->display_options['fields']['field_name_address_thoroughfare']['table'] = 'field_data_field_name_address';
$handler->display->display_options['fields']['field_name_address_thoroughfare']['field'] = 'field_name_address_thoroughfare';
$handler->display->display_options['fields']['field_name_address_thoroughfare']['relationship'] = 'profile';
$handler->display->display_options['fields']['field_name_address_thoroughfare']['label'] = 'Street address';
$handler->display->display_options['fields']['field_name_address_thoroughfare']['exclude'] = TRUE;
/* Field: Profile: Name &amp; Address - Administrative area (i.e. State / Province) */
$handler->display->display_options['fields']['field_name_address_administrative_area']['id'] = 'field_name_address_administrative_area';
$handler->display->display_options['fields']['field_name_address_administrative_area']['table'] = 'field_data_field_name_address';
$handler->display->display_options['fields']['field_name_address_administrative_area']['field'] = 'field_name_address_administrative_area';
$handler->display->display_options['fields']['field_name_address_administrative_area']['relationship'] = 'profile';
$handler->display->display_options['fields']['field_name_address_administrative_area']['label'] = 'State / Province';
$handler->display->display_options['fields']['field_name_address_administrative_area']['display_name'] = 1;
/* Field: Profile: Name &amp; Address - Locality (i.e. City) */
$handler->display->display_options['fields']['field_name_address_locality']['id'] = 'field_name_address_locality';
$handler->display->display_options['fields']['field_name_address_locality']['table'] = 'field_data_field_name_address';
$handler->display->display_options['fields']['field_name_address_locality']['field'] = 'field_name_address_locality';
$handler->display->display_options['fields']['field_name_address_locality']['relationship'] = 'profile';
$handler->display->display_options['fields']['field_name_address_locality']['label'] = 'City';
/* Field: Profile: Name &amp; Address - Postal code */
$handler->display->display_options['fields']['field_name_address_postal_code']['id'] = 'field_name_address_postal_code';
$handler->display->display_options['fields']['field_name_address_postal_code']['table'] = 'field_data_field_name_address';
$handler->display->display_options['fields']['field_name_address_postal_code']['field'] = 'field_name_address_postal_code';
$handler->display->display_options['fields']['field_name_address_postal_code']['relationship'] = 'profile';
$handler->display->display_options['fields']['field_name_address_postal_code']['label'] = 'Postal code';
$handler->display->display_options['fields']['field_name_address_postal_code']['exclude'] = TRUE;
/* Field: Profile: Name &amp; Address - Country */
$handler->display->display_options['fields']['field_name_address_country']['id'] = 'field_name_address_country';
$handler->display->display_options['fields']['field_name_address_country']['table'] = 'field_data_field_name_address';
$handler->display->display_options['fields']['field_name_address_country']['field'] = 'field_name_address_country';
$handler->display->display_options['fields']['field_name_address_country']['relationship'] = 'profile';
$handler->display->display_options['fields']['field_name_address_country']['label'] = 'Country';
$handler->display->display_options['fields']['field_name_address_country']['display_name'] = 1;
/* Field: Profile: Main Ph. */
$handler->display->display_options['fields']['field_home_ph_']['id'] = 'field_home_ph_';
$handler->display->display_options['fields']['field_home_ph_']['table'] = 'field_data_field_home_ph_';
$handler->display->display_options['fields']['field_home_ph_']['field'] = 'field_home_ph_';
$handler->display->display_options['fields']['field_home_ph_']['relationship'] = 'profile';
/* Field: Profile: Second Ph. */
$handler->display->display_options['fields']['field_mobile_ph_']['id'] = 'field_mobile_ph_';
$handler->display->display_options['fields']['field_mobile_ph_']['table'] = 'field_data_field_mobile_ph_';
$handler->display->display_options['fields']['field_mobile_ph_']['field'] = 'field_mobile_ph_';
$handler->display->display_options['fields']['field_mobile_ph_']['relationship'] = 'profile';
/* Field: User: E-mail */
$handler->display->display_options['fields']['mail']['id'] = 'mail';
$handler->display->display_options['fields']['mail']['table'] = 'users';
$handler->display->display_options['fields']['mail']['field'] = 'mail';
$handler->display->display_options['fields']['mail']['relationship'] = 'user_uid';
/* Field: Profile: DOB */
$handler->display->display_options['fields']['field_dob']['id'] = 'field_dob';
$handler->display->display_options['fields']['field_dob']['table'] = 'field_data_field_dob';
$handler->display->display_options['fields']['field_dob']['field'] = 'field_dob';
$handler->display->display_options['fields']['field_dob']['relationship'] = 'profile';
$handler->display->display_options['fields']['field_dob']['settings'] = array(
  'format_type' => 'dateexport',
  'fromto' => 'both',
  'multiple_number' => '',
  'multiple_from' => '',
  'multiple_to' => '',
  'show_remaining_days' => 0,
);
/* Field: Registration: Runner Type */
$handler->display->display_options['fields']['field_runner_type']['id'] = 'field_runner_type';
$handler->display->display_options['fields']['field_runner_type']['table'] = 'field_data_field_runner_type';
$handler->display->display_options['fields']['field_runner_type']['field'] = 'field_runner_type';
$handler->display->display_options['fields']['field_runner_type']['label'] = '';
$handler->display->display_options['fields']['field_runner_type']['exclude'] = TRUE;
$handler->display->display_options['fields']['field_runner_type']['element_label_colon'] = FALSE;
/* Field: Registration: Registration type */
$handler->display->display_options['fields']['type']['id'] = 'type';
$handler->display->display_options['fields']['type']['table'] = 'registration';
$handler->display->display_options['fields']['type']['field'] = 'type';
/* Field: Registration: Rendered Registration */
$handler->display->display_options['fields']['rendered_entity']['id'] = 'rendered_entity';
$handler->display->display_options['fields']['rendered_entity']['table'] = 'views_entity_registration';
$handler->display->display_options['fields']['rendered_entity']['field'] = 'rendered_entity';
$handler->display->display_options['fields']['rendered_entity']['exclude'] = TRUE;
$handler->display->display_options['fields']['rendered_entity']['link_to_entity'] = 1;
$handler->display->display_options['fields']['rendered_entity']['view_mode'] = 'full';
$handler->display->display_options['fields']['rendered_entity']['bypass_access'] = 0;
/* Field: Profile: Medical Condition Details */
$handler->display->display_options['fields']['field_medical_condition_details']['id'] = 'field_medical_condition_details';
$handler->display->display_options['fields']['field_medical_condition_details']['table'] = 'field_data_field_medical_condition_details';
$handler->display->display_options['fields']['field_medical_condition_details']['field'] = 'field_medical_condition_details';
$handler->display->display_options['fields']['field_medical_condition_details']['relationship'] = 'profile';
$handler->display->display_options['fields']['field_medical_condition_details']['label'] = 'Medical Conditions';
/* Field: Registration: No of Prev events */
$handler->display->display_options['fields']['field_no_of_prev_events']['id'] = 'field_no_of_prev_events';
$handler->display->display_options['fields']['field_no_of_prev_events']['table'] = 'field_data_field_no_of_prev_events';
$handler->display->display_options['fields']['field_no_of_prev_events']['field'] = 'field_no_of_prev_events';
/* Field: Registration: Medal Year */
$handler->display->display_options['fields']['field_medal_year']['id'] = 'field_medal_year';
$handler->display->display_options['fields']['field_medal_year']['table'] = 'field_data_field_medal_year';
$handler->display->display_options['fields']['field_medal_year']['field'] = 'field_medal_year';
/* Field: Registration: Previous best result */
$handler->display->display_options['fields']['field_previous_best_time']['id'] = 'field_previous_best_time';
$handler->display->display_options['fields']['field_previous_best_time']['table'] = 'field_data_field_previous_best_time';
$handler->display->display_options['fields']['field_previous_best_time']['field'] = 'field_previous_best_time';
$handler->display->display_options['fields']['field_previous_best_time']['settings'] = array(
  'format_type' => 'timeonly',
  'fromto' => 'both',
  'multiple_number' => '',
  'multiple_from' => '',
  'multiple_to' => '',
  'show_remaining_days' => 0,
);
/* Field: Registration: Year of previous best result */
$handler->display->display_options['fields']['field_year_of_previous_best_resu']['id'] = 'field_year_of_previous_best_resu';
$handler->display->display_options['fields']['field_year_of_previous_best_resu']['table'] = 'field_data_field_year_of_previous_best_resu';
$handler->display->display_options['fields']['field_year_of_previous_best_resu']['field'] = 'field_year_of_previous_best_resu';
$handler->display->display_options['fields']['field_year_of_previous_best_resu']['settings'] = array(
  'format_type' => 'yearonly',
  'fromto' => 'both',
  'multiple_number' => '',
  'multiple_from' => '',
  'multiple_to' => '',
  'show_remaining_days' => 0,
);
/* Field: Registration: Est. Time this year */
$handler->display->display_options['fields']['field_est_time_this_year']['id'] = 'field_est_time_this_year';
$handler->display->display_options['fields']['field_est_time_this_year']['table'] = 'field_data_field_est_time_this_year';
$handler->display->display_options['fields']['field_est_time_this_year']['field'] = 'field_est_time_this_year';
$handler->display->display_options['fields']['field_est_time_this_year']['settings'] = array(
  'format_type' => 'timeonly',
  'fromto' => 'both',
  'multiple_number' => '',
  'multiple_from' => '',
  'multiple_to' => '',
  'show_remaining_days' => 0,
);
/* Field: Registration: Notes */
$handler->display->display_options['fields']['field_notes']['id'] = 'field_notes';
$handler->display->display_options['fields']['field_notes']['table'] = 'field_data_field_notes';
$handler->display->display_options['fields']['field_notes']['field'] = 'field_notes';
$handler->display->display_options['fields']['field_notes']['label'] = '';
$handler->display->display_options['fields']['field_notes']['exclude'] = TRUE;
$handler->display->display_options['fields']['field_notes']['element_label_colon'] = FALSE;
/* Field: Registration: Tags */
$handler->display->display_options['fields']['field_tags']['id'] = 'field_tags';
$handler->display->display_options['fields']['field_tags']['table'] = 'field_data_field_tags';
$handler->display->display_options['fields']['field_tags']['field'] = 'field_tags';
$handler->display->display_options['fields']['field_tags']['label'] = '';
$handler->display->display_options['fields']['field_tags']['exclude'] = TRUE;
$handler->display->display_options['fields']['field_tags']['element_label_colon'] = FALSE;
$handler->display->display_options['fields']['field_tags']['type'] = 'taxonomy_term_reference_plain';
$handler->display->display_options['fields']['field_tags']['delta_offset'] = '0';
/* Field: Profile: Running profile */
$handler->display->display_options['fields']['field_running_profile']['id'] = 'field_running_profile';
$handler->display->display_options['fields']['field_running_profile']['table'] = 'field_data_field_running_profile';
$handler->display->display_options['fields']['field_running_profile']['field'] = 'field_running_profile';
$handler->display->display_options['fields']['field_running_profile']['relationship'] = 'profile';
/* Field: Profile: Commentary */
$handler->display->display_options['fields']['field_commentary']['id'] = 'field_commentary';
$handler->display->display_options['fields']['field_commentary']['table'] = 'field_data_field_commentary';
$handler->display->display_options['fields']['field_commentary']['field'] = 'field_commentary';
$handler->display->display_options['fields']['field_commentary']['relationship'] = 'profile';
/* Field: Registration: Date updated */
$handler->display->display_options['fields']['updated']['id'] = 'updated';
$handler->display->display_options['fields']['updated']['table'] = 'registration';
$handler->display->display_options['fields']['updated']['field'] = 'updated';
$handler->display->display_options['fields']['updated']['label'] = '';
$handler->display->display_options['fields']['updated']['exclude'] = TRUE;
$handler->display->display_options['fields']['updated']['element_label_colon'] = FALSE;
$handler->display->display_options['fields']['updated']['date_format'] = 'short';
$handler->display->display_options['fields']['updated']['second_date_format'] = 'long';
$handler->display->display_options['defaults']['filter_groups'] = FALSE;
$handler->display->display_options['defaults']['filters'] = FALSE;
/* Filter criterion: CurrentYear */
$handler->display->display_options['filters']['php']['id'] = 'php';
$handler->display->display_options['filters']['php']['table'] = 'views';
$handler->display->display_options['filters']['php']['field'] = 'php';
$handler->display->display_options['filters']['php']['ui_name'] = 'CurrentYear';
$handler->display->display_options['filters']['php']['group'] = 1;
$handler->display->display_options['filters']['php']['use_php_setup'] = 0;
$handler->display->display_options['filters']['php']['php_filter'] = '    $race_date = getdate(strtotime("first Saturday of December"));
    $race_year = $race_date[\'year\'];
    $reg_year = getdate($row->created)[\'year\'];
    if ($reg_year < $race_year ) {
        return TRUE; // Rows where this returns true are not displayed
    }
    else {
        return FALSE;
    }';
/* Filter criterion: Registration: State entity */
$handler->display->display_options['filters']['state']['id'] = 'state';
$handler->display->display_options['filters']['state']['table'] = 'registration';
$handler->display->display_options['filters']['state']['field'] = 'state';
$handler->display->display_options['filters']['state']['value'] = array(
  'waitlist' => 'waitlist',
  'invited' => 'invited',
  'complete' => 'complete',
  'paid' => 'paid',
);
$handler->display->display_options['filters']['state']['group'] = 1;
/* Filter criterion: Registration: Registration type */
$handler->display->display_options['filters']['type']['id'] = 'type';
$handler->display->display_options['filters']['type']['table'] = 'registration';
$handler->display->display_options['filters']['type']['field'] = 'type';
$handler->display->display_options['filters']['type']['value'] = array(
  'keplerreg' => 'keplerreg',
);
$handler->display->display_options['filters']['type']['group'] = 1;
$handler->display->display_options['path'] = 'admin/data_export/activetiming_kepler.csv';
$handler->display->display_options['sitename_title'] = 0;

/* Display: ActiveTiming Grunt Export */
$handler = $view->new_display('views_data_export', 'ActiveTiming Grunt Export', 'views_data_export_11');
$handler->display->display_options['defaults']['title'] = FALSE;
$handler->display->display_options['title'] = 'ActiveTiming Grunt Export';
$handler->display->display_options['pager']['type'] = 'none';
$handler->display->display_options['pager']['options']['offset'] = '0';
$handler->display->display_options['style_plugin'] = 'views_data_export_csv';
$handler->display->display_options['defaults']['relationships'] = FALSE;
/* Relationship: Registration: User */
$handler->display->display_options['relationships']['user_uid']['id'] = 'user_uid';
$handler->display->display_options['relationships']['user_uid']['table'] = 'registration';
$handler->display->display_options['relationships']['user_uid']['field'] = 'user_uid';
/* Relationship: User: Profile */
$handler->display->display_options['relationships']['profile']['id'] = 'profile';
$handler->display->display_options['relationships']['profile']['table'] = 'users';
$handler->display->display_options['relationships']['profile']['field'] = 'profile';
$handler->display->display_options['relationships']['profile']['relationship'] = 'user_uid';
$handler->display->display_options['relationships']['profile']['bundle_types'] = array(
  'main' => 'main',
);
/* Relationship: Registration: Registration to Node */
$handler->display->display_options['relationships']['registration_related_node']['id'] = 'registration_related_node';
$handler->display->display_options['relationships']['registration_related_node']['table'] = 'registration';
$handler->display->display_options['relationships']['registration_related_node']['field'] = 'registration_related_node';
/* Relationship: Race Numbers: Registration_ID */
$handler->display->display_options['relationships']['RegID']['id'] = 'RegID';
$handler->display->display_options['relationships']['RegID']['table'] = 'RaceNumbers';
$handler->display->display_options['relationships']['RegID']['field'] = 'RegID';
$handler->display->display_options['defaults']['fields'] = FALSE;
/* Field: Global: View result counter */
$handler->display->display_options['fields']['counter']['id'] = 'counter';
$handler->display->display_options['fields']['counter']['table'] = 'views';
$handler->display->display_options['fields']['counter']['field'] = 'counter';
$handler->display->display_options['fields']['counter']['label'] = '';
$handler->display->display_options['fields']['counter']['exclude'] = TRUE;
$handler->display->display_options['fields']['counter']['element_label_colon'] = FALSE;
$handler->display->display_options['fields']['counter']['counter_start'] = '1';
$handler->display->display_options['fields']['counter']['reverse'] = 0;
/* Field: Race Numbers: Race Number */
$handler->display->display_options['fields']['racenum']['id'] = 'racenum';
$handler->display->display_options['fields']['racenum']['table'] = 'RaceNumbers';
$handler->display->display_options['fields']['racenum']['field'] = 'racenum';
$handler->display->display_options['fields']['racenum']['relationship'] = 'RegID';
/* Field: Registration: Event Date */
$handler->display->display_options['fields']['field_year']['id'] = 'field_year';
$handler->display->display_options['fields']['field_year']['table'] = 'field_data_field_year';
$handler->display->display_options['fields']['field_year']['field'] = 'field_year';
$handler->display->display_options['fields']['field_year']['settings'] = array(
  'format_type' => 'yearonly',
  'fromto' => 'both',
  'multiple_number' => '',
  'multiple_from' => '',
  'multiple_to' => '',
  'show_remaining_days' => 0,
);
/* Field: Registration: Event Title */
$handler->display->display_options['fields']['field_event_title']['id'] = 'field_event_title';
$handler->display->display_options['fields']['field_event_title']['table'] = 'field_data_field_event_title';
$handler->display->display_options['fields']['field_event_title']['field'] = 'field_event_title';
$handler->display->display_options['fields']['field_event_title']['label'] = 'Event';
/* Field: Registration: Registration ID */
$handler->display->display_options['fields']['registration_id']['id'] = 'registration_id';
$handler->display->display_options['fields']['registration_id']['table'] = 'registration';
$handler->display->display_options['fields']['registration_id']['field'] = 'registration_id';
$handler->display->display_options['fields']['registration_id']['separator'] = '';
/* Field: Registration: State entity */
$handler->display->display_options['fields']['state']['id'] = 'state';
$handler->display->display_options['fields']['state']['table'] = 'registration';
$handler->display->display_options['fields']['state']['field'] = 'state';
$handler->display->display_options['fields']['state']['label'] = 'Status';
/* Field: Registration: User */
$handler->display->display_options['fields']['user_uid']['id'] = 'user_uid';
$handler->display->display_options['fields']['user_uid']['table'] = 'registration';
$handler->display->display_options['fields']['user_uid']['field'] = 'user_uid';
$handler->display->display_options['fields']['user_uid']['separator'] = '';
/* Field: Profile: Gender */
$handler->display->display_options['fields']['field_gender']['id'] = 'field_gender';
$handler->display->display_options['fields']['field_gender']['table'] = 'field_data_field_gender';
$handler->display->display_options['fields']['field_gender']['field'] = 'field_gender';
$handler->display->display_options['fields']['field_gender']['relationship'] = 'profile';
/* Field: Profile: Name &amp; Address - First name */
$handler->display->display_options['fields']['field_name_address_first_name']['id'] = 'field_name_address_first_name';
$handler->display->display_options['fields']['field_name_address_first_name']['table'] = 'field_data_field_name_address';
$handler->display->display_options['fields']['field_name_address_first_name']['field'] = 'field_name_address_first_name';
$handler->display->display_options['fields']['field_name_address_first_name']['relationship'] = 'profile';
$handler->display->display_options['fields']['field_name_address_first_name']['label'] = 'First name';
$handler->display->display_options['fields']['field_name_address_first_name']['exclude'] = TRUE;
/* Field: Profile: Name &amp; Address - Last name */
$handler->display->display_options['fields']['field_name_address_last_name']['id'] = 'field_name_address_last_name';
$handler->display->display_options['fields']['field_name_address_last_name']['table'] = 'field_data_field_name_address';
$handler->display->display_options['fields']['field_name_address_last_name']['field'] = 'field_name_address_last_name';
$handler->display->display_options['fields']['field_name_address_last_name']['relationship'] = 'profile';
$handler->display->display_options['fields']['field_name_address_last_name']['label'] = 'Last name';
$handler->display->display_options['fields']['field_name_address_last_name']['exclude'] = TRUE;
/* Field: Global: PHP */
$handler->display->display_options['fields']['php']['id'] = 'php';
$handler->display->display_options['fields']['php']['table'] = 'views';
$handler->display->display_options['fields']['php']['field'] = 'php';
$handler->display->display_options['fields']['php']['label'] = 'First name';
$handler->display->display_options['fields']['php']['use_php_setup'] = 0;
$handler->display->display_options['fields']['php']['php_output'] = '<?php
$op = strtoupper($row->field_name_address_first_name);
print $op;
?>';
$handler->display->display_options['fields']['php']['use_php_click_sortable'] = '0';
$handler->display->display_options['fields']['php']['php_click_sortable'] = '';
/* Field: Global: PHP */
$handler->display->display_options['fields']['php_1']['id'] = 'php_1';
$handler->display->display_options['fields']['php_1']['table'] = 'views';
$handler->display->display_options['fields']['php_1']['field'] = 'php';
$handler->display->display_options['fields']['php_1']['label'] = 'Last name';
$handler->display->display_options['fields']['php_1']['use_php_setup'] = 0;
$handler->display->display_options['fields']['php_1']['php_output'] = '<?php
$op = strtoupper($row->field_name_address_last_name);
print $op;
?>';
$handler->display->display_options['fields']['php_1']['use_php_click_sortable'] = '0';
$handler->display->display_options['fields']['php_1']['php_click_sortable'] = '';
/* Field: Profile: Name &amp; Address - Thoroughfare (i.e. Street address) */
$handler->display->display_options['fields']['field_name_address_thoroughfare']['id'] = 'field_name_address_thoroughfare';
$handler->display->display_options['fields']['field_name_address_thoroughfare']['table'] = 'field_data_field_name_address';
$handler->display->display_options['fields']['field_name_address_thoroughfare']['field'] = 'field_name_address_thoroughfare';
$handler->display->display_options['fields']['field_name_address_thoroughfare']['relationship'] = 'profile';
$handler->display->display_options['fields']['field_name_address_thoroughfare']['label'] = 'Street address';
$handler->display->display_options['fields']['field_name_address_thoroughfare']['exclude'] = TRUE;
/* Field: Profile: Name &amp; Address - Administrative area (i.e. State / Province) */
$handler->display->display_options['fields']['field_name_address_administrative_area']['id'] = 'field_name_address_administrative_area';
$handler->display->display_options['fields']['field_name_address_administrative_area']['table'] = 'field_data_field_name_address';
$handler->display->display_options['fields']['field_name_address_administrative_area']['field'] = 'field_name_address_administrative_area';
$handler->display->display_options['fields']['field_name_address_administrative_area']['relationship'] = 'profile';
$handler->display->display_options['fields']['field_name_address_administrative_area']['label'] = 'State / Province';
$handler->display->display_options['fields']['field_name_address_administrative_area']['display_name'] = 1;
/* Field: Profile: Name &amp; Address - Locality (i.e. City) */
$handler->display->display_options['fields']['field_name_address_locality']['id'] = 'field_name_address_locality';
$handler->display->display_options['fields']['field_name_address_locality']['table'] = 'field_data_field_name_address';
$handler->display->display_options['fields']['field_name_address_locality']['field'] = 'field_name_address_locality';
$handler->display->display_options['fields']['field_name_address_locality']['relationship'] = 'profile';
$handler->display->display_options['fields']['field_name_address_locality']['label'] = 'City';
/* Field: Profile: Name &amp; Address - Postal code */
$handler->display->display_options['fields']['field_name_address_postal_code']['id'] = 'field_name_address_postal_code';
$handler->display->display_options['fields']['field_name_address_postal_code']['table'] = 'field_data_field_name_address';
$handler->display->display_options['fields']['field_name_address_postal_code']['field'] = 'field_name_address_postal_code';
$handler->display->display_options['fields']['field_name_address_postal_code']['relationship'] = 'profile';
$handler->display->display_options['fields']['field_name_address_postal_code']['label'] = 'Postal code';
$handler->display->display_options['fields']['field_name_address_postal_code']['exclude'] = TRUE;
/* Field: Profile: Name &amp; Address - Country */
$handler->display->display_options['fields']['field_name_address_country']['id'] = 'field_name_address_country';
$handler->display->display_options['fields']['field_name_address_country']['table'] = 'field_data_field_name_address';
$handler->display->display_options['fields']['field_name_address_country']['field'] = 'field_name_address_country';
$handler->display->display_options['fields']['field_name_address_country']['relationship'] = 'profile';
$handler->display->display_options['fields']['field_name_address_country']['label'] = 'Country';
$handler->display->display_options['fields']['field_name_address_country']['display_name'] = 1;
/* Field: Profile: Main Ph. */
$handler->display->display_options['fields']['field_home_ph_']['id'] = 'field_home_ph_';
$handler->display->display_options['fields']['field_home_ph_']['table'] = 'field_data_field_home_ph_';
$handler->display->display_options['fields']['field_home_ph_']['field'] = 'field_home_ph_';
$handler->display->display_options['fields']['field_home_ph_']['relationship'] = 'profile';
/* Field: Profile: Second Ph. */
$handler->display->display_options['fields']['field_mobile_ph_']['id'] = 'field_mobile_ph_';
$handler->display->display_options['fields']['field_mobile_ph_']['table'] = 'field_data_field_mobile_ph_';
$handler->display->display_options['fields']['field_mobile_ph_']['field'] = 'field_mobile_ph_';
$handler->display->display_options['fields']['field_mobile_ph_']['relationship'] = 'profile';
/* Field: User: E-mail */
$handler->display->display_options['fields']['mail']['id'] = 'mail';
$handler->display->display_options['fields']['mail']['table'] = 'users';
$handler->display->display_options['fields']['mail']['field'] = 'mail';
$handler->display->display_options['fields']['mail']['relationship'] = 'user_uid';
/* Field: Profile: DOB */
$handler->display->display_options['fields']['field_dob']['id'] = 'field_dob';
$handler->display->display_options['fields']['field_dob']['table'] = 'field_data_field_dob';
$handler->display->display_options['fields']['field_dob']['field'] = 'field_dob';
$handler->display->display_options['fields']['field_dob']['relationship'] = 'profile';
$handler->display->display_options['fields']['field_dob']['settings'] = array(
  'format_type' => 'dateexport',
  'fromto' => 'both',
  'multiple_number' => '',
  'multiple_from' => '',
  'multiple_to' => '',
  'show_remaining_days' => 0,
);
/* Field: Registration: Runner Type */
$handler->display->display_options['fields']['field_runner_type']['id'] = 'field_runner_type';
$handler->display->display_options['fields']['field_runner_type']['table'] = 'field_data_field_runner_type';
$handler->display->display_options['fields']['field_runner_type']['field'] = 'field_runner_type';
$handler->display->display_options['fields']['field_runner_type']['label'] = '';
$handler->display->display_options['fields']['field_runner_type']['exclude'] = TRUE;
$handler->display->display_options['fields']['field_runner_type']['element_label_colon'] = FALSE;
/* Field: Registration: Registration type */
$handler->display->display_options['fields']['type']['id'] = 'type';
$handler->display->display_options['fields']['type']['table'] = 'registration';
$handler->display->display_options['fields']['type']['field'] = 'type';
/* Field: Registration: Rendered Registration */
$handler->display->display_options['fields']['rendered_entity']['id'] = 'rendered_entity';
$handler->display->display_options['fields']['rendered_entity']['table'] = 'views_entity_registration';
$handler->display->display_options['fields']['rendered_entity']['field'] = 'rendered_entity';
$handler->display->display_options['fields']['rendered_entity']['exclude'] = TRUE;
$handler->display->display_options['fields']['rendered_entity']['link_to_entity'] = 1;
$handler->display->display_options['fields']['rendered_entity']['view_mode'] = 'full';
$handler->display->display_options['fields']['rendered_entity']['bypass_access'] = 0;
/* Field: Profile: Medical Condition Details */
$handler->display->display_options['fields']['field_medical_condition_details']['id'] = 'field_medical_condition_details';
$handler->display->display_options['fields']['field_medical_condition_details']['table'] = 'field_data_field_medical_condition_details';
$handler->display->display_options['fields']['field_medical_condition_details']['field'] = 'field_medical_condition_details';
$handler->display->display_options['fields']['field_medical_condition_details']['relationship'] = 'profile';
$handler->display->display_options['fields']['field_medical_condition_details']['label'] = 'Medical Conditions';
/* Field: Registration: No of Prev events */
$handler->display->display_options['fields']['field_no_of_prev_events']['id'] = 'field_no_of_prev_events';
$handler->display->display_options['fields']['field_no_of_prev_events']['table'] = 'field_data_field_no_of_prev_events';
$handler->display->display_options['fields']['field_no_of_prev_events']['field'] = 'field_no_of_prev_events';
/* Field: Registration: Medal Year */
$handler->display->display_options['fields']['field_medal_year']['id'] = 'field_medal_year';
$handler->display->display_options['fields']['field_medal_year']['table'] = 'field_data_field_medal_year';
$handler->display->display_options['fields']['field_medal_year']['field'] = 'field_medal_year';
/* Field: Registration: Previous best result */
$handler->display->display_options['fields']['field_previous_best_time']['id'] = 'field_previous_best_time';
$handler->display->display_options['fields']['field_previous_best_time']['table'] = 'field_data_field_previous_best_time';
$handler->display->display_options['fields']['field_previous_best_time']['field'] = 'field_previous_best_time';
$handler->display->display_options['fields']['field_previous_best_time']['settings'] = array(
  'format_type' => 'timeonly',
  'fromto' => 'both',
  'multiple_number' => '',
  'multiple_from' => '',
  'multiple_to' => '',
  'show_remaining_days' => 0,
);
/* Field: Registration: Year of previous best result */
$handler->display->display_options['fields']['field_year_of_previous_best_resu']['id'] = 'field_year_of_previous_best_resu';
$handler->display->display_options['fields']['field_year_of_previous_best_resu']['table'] = 'field_data_field_year_of_previous_best_resu';
$handler->display->display_options['fields']['field_year_of_previous_best_resu']['field'] = 'field_year_of_previous_best_resu';
$handler->display->display_options['fields']['field_year_of_previous_best_resu']['settings'] = array(
  'format_type' => 'yearonly',
  'fromto' => 'both',
  'multiple_number' => '',
  'multiple_from' => '',
  'multiple_to' => '',
  'show_remaining_days' => 0,
);
/* Field: Registration: Est. Time this year */
$handler->display->display_options['fields']['field_est_time_this_year']['id'] = 'field_est_time_this_year';
$handler->display->display_options['fields']['field_est_time_this_year']['table'] = 'field_data_field_est_time_this_year';
$handler->display->display_options['fields']['field_est_time_this_year']['field'] = 'field_est_time_this_year';
$handler->display->display_options['fields']['field_est_time_this_year']['settings'] = array(
  'format_type' => 'timeonly',
  'fromto' => 'both',
  'multiple_number' => '',
  'multiple_from' => '',
  'multiple_to' => '',
  'show_remaining_days' => 0,
);
/* Field: Registration: Notes */
$handler->display->display_options['fields']['field_notes']['id'] = 'field_notes';
$handler->display->display_options['fields']['field_notes']['table'] = 'field_data_field_notes';
$handler->display->display_options['fields']['field_notes']['field'] = 'field_notes';
$handler->display->display_options['fields']['field_notes']['label'] = '';
$handler->display->display_options['fields']['field_notes']['exclude'] = TRUE;
$handler->display->display_options['fields']['field_notes']['element_label_colon'] = FALSE;
/* Field: Registration: Tags */
$handler->display->display_options['fields']['field_tags']['id'] = 'field_tags';
$handler->display->display_options['fields']['field_tags']['table'] = 'field_data_field_tags';
$handler->display->display_options['fields']['field_tags']['field'] = 'field_tags';
$handler->display->display_options['fields']['field_tags']['label'] = '';
$handler->display->display_options['fields']['field_tags']['exclude'] = TRUE;
$handler->display->display_options['fields']['field_tags']['element_label_colon'] = FALSE;
$handler->display->display_options['fields']['field_tags']['type'] = 'taxonomy_term_reference_plain';
$handler->display->display_options['fields']['field_tags']['delta_offset'] = '0';
/* Field: Profile: Running profile */
$handler->display->display_options['fields']['field_running_profile']['id'] = 'field_running_profile';
$handler->display->display_options['fields']['field_running_profile']['table'] = 'field_data_field_running_profile';
$handler->display->display_options['fields']['field_running_profile']['field'] = 'field_running_profile';
$handler->display->display_options['fields']['field_running_profile']['relationship'] = 'profile';
/* Field: Profile: Commentary */
$handler->display->display_options['fields']['field_commentary']['id'] = 'field_commentary';
$handler->display->display_options['fields']['field_commentary']['table'] = 'field_data_field_commentary';
$handler->display->display_options['fields']['field_commentary']['field'] = 'field_commentary';
$handler->display->display_options['fields']['field_commentary']['relationship'] = 'profile';
/* Field: Registration: Date updated */
$handler->display->display_options['fields']['updated']['id'] = 'updated';
$handler->display->display_options['fields']['updated']['table'] = 'registration';
$handler->display->display_options['fields']['updated']['field'] = 'updated';
$handler->display->display_options['fields']['updated']['label'] = '';
$handler->display->display_options['fields']['updated']['exclude'] = TRUE;
$handler->display->display_options['fields']['updated']['element_label_colon'] = FALSE;
$handler->display->display_options['fields']['updated']['date_format'] = 'short';
$handler->display->display_options['fields']['updated']['second_date_format'] = 'long';
$handler->display->display_options['defaults']['filter_groups'] = FALSE;
$handler->display->display_options['defaults']['filters'] = FALSE;
/* Filter criterion: CurrentYear */
$handler->display->display_options['filters']['php']['id'] = 'php';
$handler->display->display_options['filters']['php']['table'] = 'views';
$handler->display->display_options['filters']['php']['field'] = 'php';
$handler->display->display_options['filters']['php']['ui_name'] = 'CurrentYear';
$handler->display->display_options['filters']['php']['group'] = 1;
$handler->display->display_options['filters']['php']['use_php_setup'] = 0;
$handler->display->display_options['filters']['php']['php_filter'] = '    $race_date = getdate(strtotime("first Saturday of December"));
    $race_year = $race_date[\'year\'];
    $reg_year = getdate($row->created)[\'year\'];
    if ($reg_year < $race_year ) {
        return TRUE; // Rows where this returns true are not displayed
    }
    else {
        return FALSE;
    }';
/* Filter criterion: Registration: State entity */
$handler->display->display_options['filters']['state']['id'] = 'state';
$handler->display->display_options['filters']['state']['table'] = 'registration';
$handler->display->display_options['filters']['state']['field'] = 'state';
$handler->display->display_options['filters']['state']['value'] = array(
  'waitlist' => 'waitlist',
  'invited' => 'invited',
  'complete' => 'complete',
  'paid' => 'paid',
);
$handler->display->display_options['filters']['state']['group'] = 1;
/* Filter criterion: Registration: Registration type */
$handler->display->display_options['filters']['type']['id'] = 'type';
$handler->display->display_options['filters']['type']['table'] = 'registration';
$handler->display->display_options['filters']['type']['field'] = 'type';
$handler->display->display_options['filters']['type']['value'] = array(
  'gruntreg' => 'gruntreg',
);
$handler->display->display_options['filters']['type']['group'] = 1;
$handler->display->display_options['path'] = 'admin/data_export/activetiming_grunt.csv';
$handler->display->display_options['sitename_title'] = 0;
